src/config/settings/base.py
src/firstvoices/backend/models/app.py
src/firstvoices/backend/models/constants.py
src/firstvoices/backend/predicates/base.py
src/firstvoices/backend/predicates/utils.py
src/firstvoices/backend/tests/factories.py
src/firstvoices/backend/tests/test_predicates/test_predicate_base.py
src/firstvoices/backend/tests/test_predicates/test_predicate_utils.py
src/firstvoices/backend/tests/test_predicates/test_predicate_view.py
src/firstvoices/backend/tests/test_predicates/test_predicate_view_models.py

* new app-level membership model
* updated predicates and tests
* updated all integer-keyed enums to have gaps, for future-proofing

Fw 4178, staff and superadmin roles

---

.gitignore
README.md
reset-local-database.sh
src/reset-local-database.sh

These changes add the following for ease of local development:

FW-4181 Add script to automate local database cleaning, migrations, and superuser creation

---

.github/pull_request_template.md

This change adds a PR template which will show up in the comment section when new PRs are opened. It will appear the same as this comment. Any suggestions for changes are more than welcome.
N/A

FW-4253 Add initial PR template

---

firstvoices/backend/tests/test_apis/test_dictionary_api.py
firstvoices/backend/tests/test_apis/test_parts_of_speech_api.py
firstvoices/backend/tests/test_apis/test_sites_api.py
firstvoices/backend/tests/test_models/test_alphabet_model.py
firstvoices/backend/tests/test_models/test_dictionary_entry_model.py
firstvoices/backend/tests/test_models/test_parts_of_speech_model.py
firstvoices/backend/tests/test_predicates/test_predicate_base.py
firstvoices/backend/tests/test_predicates/test_predicate_utils.py

These changes remove the loading of default fixtures in tests since this is now done in migrations.
N/A

Remove default fixture loading in tests

---

README.md

This PR updates the README to match the current repo state.
N/A

FW-4318 Update README.md

---

firstvoices/backend/tests/test_apis/test_my_sites_api.py

Remove language grouping from my-sites API tests

---

firstvoices/backend/serializers/dictionary_serializers.py
firstvoices/backend/serializers/site_serializers.py
firstvoices/backend/tests/test_apis/test_dictionary_api.py
firstvoices/backend/tests/test_apis/test_sites_api.py
firstvoices/backend/views/dictionary_views.py

- permissions enforced on related entry list
- bonus: added IDs to all list items in responses (request from Guy)
N/A

fw-4321, add related entries to dictionary api

---

firstvoices/backend/admin/app_admin.py

Added an admin form for the App-level Membership model (staff and superadmin roles)
N/A

fw-4381, admin for superadmin roles

---

README.md
firstvoices/backend/jwt_auth.py
firstvoices/backend/views/data_views.py
firstvoices/firstvoices/settings.py

- allow guest user access
- fix a code smell in the jwt auth code (it was catching redundant exceptions)
- enforce permissions on site data export dictionary data
N/A

Fw-4397, access for app developers

---

firstvoices/backend/jwt_auth.py
firstvoices/firstvoices/settings.py

- allow guest access in our custom jwt auth
- allow guest access to api docs
N/A

fw-4397, more fixes for app developer access

---

firstvoices/backend/jwt_auth.py

Last fix for guest access.
N/A

fw-4397, return Anon instead of None

---

firstvoices/backend/models/dictionary.py
firstvoices/backend/serializers/site_serializers.py
firstvoices/backend/tests/test_apis/test_sites_api.py
firstvoices/backend/views/word_of_the_day_views.py

Fixed a bug that was returning incorrect word when requested for the oldest word of the day.
N/A

word of the day - oldest word bug

---

firstvoices/backend/views/word_of_the_day_views.py

- ~Review the code changes here~
N/A

Fixed site filter bug in word of the day api

---

README.md

Updated readme to add instructions about using docker for local elastic search instance.
N/A

Fw 4303 set up docker for local elastic search development

---

README.md
firstvoices/firstvoices/settings.py
requirements.txt

This PR adds the Sentry SDK to the project, which will send information to the Sentry dashboard (links in Jira ticket).
N/A

FW-4133 Add Sentry Integration

---

firstvoices/firstvoices/settings.py

Update CORS allowed origins to include https://localhost:3000
N/A

Update CORS allowed origins

---

firstvoices/backend/models/category.py
firstvoices/backend/tests/test_apis/base_api_test.py
firstvoices/backend/tests/test_apis/test_category_api.py
firstvoices/backend/tests/test_apis/test_characters_api.py
firstvoices/backend/tests/test_apis/test_dictionary_api.py
firstvoices/backend/tests/test_apis/test_ignored_characters_api.py
firstvoices/backend/views/category_views.py
firstvoices/backend/views/doc_strings.py

* delete API for the categories. (Always the easiest kind of API!)
* includes a test mixin for delete APIs
* bonus change: made some constants for standard error descriptions etc in our api docs
* bonus change: updated the category api tests to pull in all the relevant mixins
N/A

Fw-4212, delete API for categories

---

firstvoices/backend/tests/test_apis/test_dictionary_api.py

Sorry gang, this should unblock some open PRs with failing tests
N/A

fw-4212, fix bad import after merge

---

firstvoices/backend/serializers/base_serializers.py
firstvoices/backend/serializers/category_serializers.py
firstvoices/backend/tests/test_apis/base_api_test.py
firstvoices/backend/views/base_views.py
firstvoices/backend/views/category_views.py

* update FVPermissionViewSetMixin to allow checking create permissions per site rather than on a null object
* serializer mixins for create APIs
* test mixin for create APIs
N/A

Fw-4212, category create api

---

firstvoices/backend/serializers/site_serializers.py
firstvoices/backend/tests/test_apis/test_sites_api.py
firstvoices/backend/views/sites_views.py

features are used by the explore languages page, so include that info in the site list api
N/A

fw-4431, include site features in list api

---

firstvoices/backend/search/query_builder.py

Indendation fix in query_builder

---

firstvoices/backend/admin/dictionary_admin.py
firstvoices/backend/serializers/dictionary_serializers.py
firstvoices/backend/tests/test_apis/test_characters_api.py
firstvoices/backend/tests/test_apis/test_dictionary_api.py

* add some fields to related entries in dictionary api (needed in frontend)
* un-hide dictionary entries in the admin site
N/A

fw-4480, add fields to related entries

---

firstvoices/backend/router.py
firstvoices/backend/serializers/site_serializers.py
firstvoices/backend/tests/test_apis/test_characters_api.py
firstvoices/backend/tests/test_apis/test_dictionary_api.py
firstvoices/backend/tests/test_apis/test_dictionary_cleanup_api.py
firstvoices/backend/tests/test_apis/test_sites_api.py
firstvoices/backend/urls.py

Support urls with or without trailing slashes, by adding a custom router that slightly modifies the regex used for url matching. This is better than the old method of appending trailing slashes, because modifying URLs required forwarding requests to the new URLs and that didn't work properly for PUT and DELETE requests.
N/A

fw-4461, fix trailing slash situation

---

firstvoices/firstvoices/settings.py

For generating absolute URLs in responses
N/A

fw-4476, use https within django

---

Dockerfile
firstvoices/backend/models/dictionary.py

fw-4320, sonar fixes for main branch

---

firstvoices/backend/management/commands/_helper.py
firstvoices/backend/search/indices/dictionary_entry_document.py
firstvoices/backend/search/query_builder.py
firstvoices/backend/search/utils/query_builder_utils.py
firstvoices/backend/tests/test_search/test_filters.py
firstvoices/backend/views/search/base_search_views.py

Added kids and games flags to base search API.
N/A

Fw 4419 add kids and games parameters to search api

---

firstvoices/backend/search/indices/dictionary_entry_document.py
firstvoices/backend/search/utils/object_utils.py

For whatever reason, the mock elasticsearch server on my computer was returning 404 errors instead of empty search results. A good prompt to handle that edge case, so here is the small update to do it.
N/A

fw-4568, handle 404 from es server

---

firstvoices/backend/search/indices/dictionary_entry_document.py

Added signals for categories m2m update.
N/A

added signal for category update

---

firstvoices/backend/serializers/site_serializers.py
firstvoices/backend/serializers/widget_serializers.py
firstvoices/backend/tests/test_apis/test_sites_api.py
firstvoices/backend/tests/test_apis/test_widgets_api.py
firstvoices/backend/urls.py
firstvoices/backend/views/widget_views.py

This PR adds the read API for widgets associated with a site. There is a list view which returns all visible widgets for a site, as well as a detail view that returns information about a specific widget for a site by ID.
Widget lists (`SiteWidgetList` model) will be accessed and managed through the page model API and the homepage field on the site model (will be added in FW-4331, FW-4560, and FW-4329).
```json
{
"count": 2,
"pages": 1,
"pageSize": 100,
"next": null,
"nextUrl": null,
"previous": null,
"previousUrl": null,
"results": [
{
"id": "bf0d25bf-0beb-499f-bbdc-5855ca8545ea",
"title": "TestSiteWidget1",
"url": "http://localhost:8000/api/1.0/sites/test-site/site-widgets/bf0d25bf-0beb-499f-bbdc-5855ca8545ea",
"visibility": "Public",
"widgetType": "WIDGET_TEXT",
"format": "Default", …
```

FW-4330 Add SiteWidgets read API

---

firstvoices/backend/views/search/dictionary_search_views.py

Invalid category id's were being invalidated but a return statement was missing which would return empty results for invalid case. Added that.
N/A

FW-4576  dictionary-search invalid category fix

---

firstvoices/backend/admin/admin.py
firstvoices/backend/search/indices/dictionary_entry_document.py

Adds a signal to change the visibility of ES documents if a site's visibility is changed. Nice catch Sahil!
N/A

FW-4418 Add Visibility Site Signal

---

firstvoices/backend/serializers/site_serializers.py

Added a fix for a bug was allowing the PUT request to bypass validators.
N/A

Moved title from meta to serializer fields

---

firstvoices/backend/serializers/dictionary_serializers.py
firstvoices/backend/tests/test_apis/test_dictionary_api.py

Adds related entries and associated tests to the dictionary write API.
N/A

FW-4604 Add Related Entries to Dictionary API

---

firstvoices/backend/models/media.py
firstvoices/backend/serializers/category_serializers.py
firstvoices/backend/serializers/media_serializers.py
firstvoices/backend/serializers/site_serializers.py
firstvoices/backend/serializers/validators.py
firstvoices/backend/tests/factories/story_factories.py
firstvoices/backend/tests/test_apis/base_media_test.py
firstvoices/backend/tests/test_apis/test_audio_api.py
firstvoices/backend/tests/test_apis/test_story_api.py
firstvoices/backend/tests/test_search/test_query_builder_utils.py
firstvoices/backend/tests/test_search/test_query_params.py
firstvoices/backend/tests/test_serializers.py

- add file type validation for media create APIs
- a few test cleanup things
N/A

Fw-4215, media validation

---

firstvoices/jwt_auth/managers.py
firstvoices/reset-local-database.sh
firstvoices/scripts/create_local_superadmin_membership.py

Update manager functions with changes to id and sub fields in the user model
N/A

fw-4608, fix create_superuser function

---

firstvoices/backend/views/base_views.py

Fix for duplicated data returned from APIs

---

firstvoices/backend/management/commands/_helper.py
firstvoices/backend/management/commands/rebuild_index.py
firstvoices/backend/search/indices/__init__.py
firstvoices/backend/search/indices/story_document.py
firstvoices/backend/search/utils/constants.py
firstvoices/backend/search/utils/object_utils.py
firstvoices/backend/search/utils/query_builder_utils.py
firstvoices/backend/tests/test_search/test_query_builder_utils.py
firstvoices/backend/views/search/base_search_views.py

Fw 4270 implement story search with parameters

---

firstvoices/backend/management/commands/_helper.py
firstvoices/backend/search/indices/story_document.py

Added author field to story document for searching purposes.
N/A

FW-4651 - Add author to Story search document

---

firstvoices/backend/serializers/story_serializers.py

Adding the second half of the create permission checking
N/A

fw-4368, fix create permission for story page api

---

firstvoices/backend/resources/users.py
firstvoices/backend/tests/test_resources/__init__.py
firstvoices/backend/tests/test_resources/test_user_resource.py
firstvoices/jwt_auth/models.py
firstvoices/scripts/import_csv_data.py

Adds the import of users via the UserResource
N/A

FW-4446 Import Users

---

firstvoices/backend/search/indices/dictionary_entry_document.py
firstvoices/backend/search/indices/song_document.py
firstvoices/backend/search/indices/story_document.py
firstvoices/backend/search/utils/object_utils.py
firstvoices/backend/search/utils/site_signals.py
firstvoices/firstvoices/settings.py

Added fallback exception handling for all signals related to Elasticsearch.
N/A

FW-4693 Handle ES exception when server is down

---

firstvoices/backend/search/utils/object_utils.py

added timeout to search request in get_object_from_index

---

firstvoices/backend/serializers/category_serializers.py
firstvoices/backend/serializers/dictionary_serializers.py

- allows blank in category descriptions
- removed redundant category serializer
N/A

FW-4707 Allow blank in category descriptions

---

firstvoices/backend/admin/base_admin.py
firstvoices/backend/admin/dictionary_admin.py
firstvoices/backend/admin/story_admin.py
firstvoices/backend/models/story.py

- remove unnecessary drop-downs in inline forms
- prefetch some properties
- auto-set some fields (e.g., site for story pages) to avoid a dropdown list
N/A

fw-4735, faster admin forms

---

firstvoices/backend/admin/admin.py
firstvoices/backend/admin/base_admin.py
firstvoices/backend/admin/characters_admin.py
firstvoices/backend/admin/dictionary_admin.py
firstvoices/backend/admin/sites_admin.py
firstvoices/backend/admin/story_admin.py

- prefetch fields required for model string display
N/A

fw-4725, more admin fixes

---

firstvoices/backend/admin/base_admin.py
firstvoices/backend/admin/widget_admin.py

Fix BaseAdmin fields

---

.github/dependabot.yml
requirements.txt

fw-4679, downgrade elasticsearch to work on prod

---

firstvoices/backend/admin/sites_admin.py

- avoids an error in sentry about the non-existant username
N/A

fw-4735, fix user lookup in membership admin

---

firstvoices/backend/resources/characters.py
firstvoices/backend/tests/test_resources/test_character_resource.py

added handling for missing media files
N/A

FW-4772 handling missing media files

---

firstvoices/backend/serializers/media_serializers.py
firstvoices/backend/views/audio_views.py
firstvoices/backend/views/category_views.py
firstvoices/backend/views/character_views.py
firstvoices/backend/views/dictionary_views.py
firstvoices/backend/views/image_views.py
firstvoices/backend/views/sites_views.py
firstvoices/backend/views/utils.py
firstvoices/backend/views/video_views.py

- whole lotta prefetching, with some reusable parts
- some APIs require more in-depth optimization so I logged separate tickets for another time (e.g., categories)
- more APIs coming in a separate PR (pages, songs, stories) but I wanted to get these into today's beta update if possible
N/A

fw-4748, API db performance improvements

---

firstvoices/backend/search/utils/query_builder_utils.py

removed lowercasing for input strings in parameter startsWithChar for search API
N/A

FW-4779 alphabet all results should have searched letter at the beginning

---

firstvoices/backend/views/page_views.py
firstvoices/backend/views/song_views.py
firstvoices/backend/views/story_views.py

- prefetching as appropriate to reduce db queries
- bonus: songs and stories lists ordered by title instead of uid
N/A

fw-4748, db opts for pages api

---

firstvoices/backend/search/indices/base_document.py

edited base document to make id to a keyword field

---

firstvoices/backend/resources/characters.py
firstvoices/backend/tests/test_resources/test_character_resource.py

Fixes an issue where base characters with blank related media would not import due to the field being empty.
N/A

FW-4799 Fix base character import

---

firstvoices/backend/serializers/media_serializers.py

Added x-wav to mimetype list for audios
N/A

FW-4785 v3 dashboard wav upload fix

---

firstvoices/backend/management/commands/_helper.py
firstvoices/backend/management/commands/import_csv_data.py

Disconnect signals before import and re-connect signals after import.
N/A

Fw 4811 pause indexing while migration

---

firstvoices/backend/serializers/media_serializers.py
firstvoices/backend/serializers/validators.py

- Add more mp3 container format mimetypes
- More informative error message that tells you the mimetype of the file you tried to upload
N/A

fw-4829, better audio upload support

---

firstvoices/firstvoices/settings.py

fw-4403, display sentry environment name in admin banner

---

firstvoices/firstvoices/settings.py

* Add the "Content-Disposition: attachment" header for uploaded media, so users will be prompted to download it rather than having it display in their browser
N/A

fw-4793, set Content-Disposition for uploaded files

---

firstvoices/backend/admin/admin.py
firstvoices/backend/admin/base_admin.py
firstvoices/backend/admin/characters_admin.py
firstvoices/backend/admin/dictionary_admin.py
firstvoices/backend/admin/page_admin.py
firstvoices/backend/admin/sites_admin.py
firstvoices/backend/admin/widget_admin.py
firstvoices/backend/models/dictionary.py

Added improved site-by-site filtering for content on misc admin forms, with particular attention to the Site form and Character forms (addressing some of FW-4234). There is now a site filter in various admin lists. Dropdowns now only contain content from the same site (this fixes WOTD bug FW-4405). The filtered queries improve admin site performance/load times.
N/A

FW-4234 improved admin forms

---

firstvoices/backend/admin/app_admin.py

fw-4890, fix user search in AppMembership admin list

---

firstvoices/backend/management/commands/import_csv_data.py
firstvoices/backend/resources/songs.py

Made a fix in the import script to allow the same CSV to be imported with different resources. Also fixed metadata which was missing from songs/lyrics migration.
N/A

FW-4775 FW-4747 fix songs/homepage import

---

firstvoices/backend/views/audio_views.py
firstvoices/backend/views/image_views.py
firstvoices/backend/views/video_views.py

fw-4814, define list order for media APIs

---

firstvoices/backend/admin/base_admin.py

This PR fixes the small bug when creating a site on the admin forms.
N/A

FW-4913 Fix site creation via admin site

---

firstvoices/backend/serializers/page_serializers.py

This PR adds validation when attempting to create pages with duplicate slugs across a site.
N/A

FW-4876 Add duplicate page slug validation

---

firstvoices/backend/serializers/base_serializers.py
firstvoices/backend/serializers/fields.py
firstvoices/backend/serializers/song_serializers.py
firstvoices/backend/tests/test_apis/base_api_test.py
firstvoices/backend/tests/test_apis/test_dictionary_api.py
firstvoices/backend/tests/test_apis/test_pages_api.py
firstvoices/backend/tests/test_apis/test_sites_api.py
firstvoices/backend/tests/test_apis/test_song_api.py
firstvoices/backend/tests/test_apis/test_story_api.py
firstvoices/backend/tests/test_apis/test_storypage_api.py
firstvoices/backend/tests/test_apis/test_widgets_api.py

Converts all instances of visibility in the API to lowercase as per the spec for FW-4769
Bonus change: fixes flakiness for `test_detail_homepage`
When this is merged there will be breaking changes and the FE will need to be altered accordingly. CC @gmcauliffe

FW-4769 Consistently show lowercase visibility in API

---

firstvoices/backend/search/utils/object_utils.py
firstvoices/backend/search/utils/site_signals.py

- Added story update and delete methods when a site is updated/deleted.
- Added fallback exception handling in case there are any orphan objects left in search index.
N/A

Fw 4941 site attribute missing from search objects throws error

---

requirements.txt

Latest update is breaking the build (lack of support for our python version i think)
N/A

downgrade numpy

---

firstvoices/backend/views/dictionary_views.py
firstvoices/backend/views/image_views.py
firstvoices/backend/views/video_views.py

This PR adds some small optimizations to the Image/Video/Dictionary list views, improving the latency of the database queries.
N/A

FW-4937 Image/Video/Dictionary list view performance improvements

---

requirements.txt

Tests coming in another PR 
N/A

fw-4946, downgrade django-storages to fix thumbnails

---

firstvoices/firstvoices/settings.py

Fw 4756 deployment settings

---

firstvoices/firstvoices/settings.py

* Set Cache-Control headers for uploaded files. (Once this is tested, we may want to go set it for all migrated media as well.)
N/A

fw-4957, update cache settings for AWS media

---

firstvoices/backend/search/utils/object_utils.py
firstvoices/backend/serializers/media_serializers.py

Added speakers field to AudioMinimalSerializer
N/A

FW-4943 Added more fields to AudioMinimalSerializer

---

firstvoices/backend/models/media.py

This PR updates the image thumbnail generation to keep the original quality if the original image size is smaller than the thumbnail size (quality was increased leading to cases of larger files with the same image dimensions being generated).
For thumbnails that are smaller than the original image, the quality has been reduced to 80 from 90 as there is no noticeable difference to the human eye.
N/A

FW-4971 Update image thumbnail generation quality

---

firstvoices/backend/tests/test_apis/test_category_api.py
firstvoices/backend/views/category_views.py
firstvoices/backend/views/sites_views.py
firstvoices/backend/views/utils.py

This PR fixes several of the N+1 query issues including the categories list view and views that prefetch related media.
N/A

FW-4949 N+1 query fixes

---

firstvoices/backend/models/media.py
firstvoices/firstvoices/settings.py

* To test whether the cache-breaking effects of the querystrings are affecting our server performance
N/A

fw-4813, disable s3 auth querystrings on media

---

firstvoices/backend/serializers/page_serializers.py

- fixed a bug that was passing a sitePage instance of a site to the create method for SiteWidgetList
N/A

Bug fix for SiteWidgetList create method

---

firstvoices/backend/views/sites_views.py
firstvoices/backend/views/widget_views.py

This PR adds additional select_related calls to the site detail and widget views, reducing the number of database queries, lowering the query time, and fixing N+1 sentry issues.
N/A

FW-4949 Add select_related to site detail and widget views

---

firstvoices/backend/serializers/base_serializers.py
firstvoices/backend/tests/test_apis/test_song_api.py
firstvoices/backend/tests/test_apis/test_story_api.py
firstvoices/backend/tests/test_apis/test_storypage_api.py

Accept object-format data for notes and acknowledgements, and treat the "text" property as the value.
N/A

fw-4991, write song + story notes and acks

---

firstvoices/backend/management/commands/convert_lyrics_draftjs_to_text.py
firstvoices/backend/tests/test_commands/test_convert_lyrics_draftjs_to_text.py

This change fixes a small issue with the lyric draftjs to text converter.
N/A

FW-4995 Fix draftjs to text missing blocks key error

---

README.md
firstvoices/backend/search/__init__.py
firstvoices/backend/search/documents/__init__.py
firstvoices/backend/search/documents/media_document.py
firstvoices/backend/search/signals/media_signals.py
firstvoices/backend/search/tasks/media_tasks.py
firstvoices/backend/search/utils/constants.py
firstvoices/backend/tests/conftest.py
firstvoices/backend/tests/test_apis/test_pages_api.py

- Added ES document for media files
- Added signals and tasks for update the index for CUD operations related to media
N/A

Fw 5059 add index documents for media

---

.github/workflows/build.yml
README.md
firstvoices/.coveragerc
firstvoices/backend/tests/test_apis/test_sites_api.py
firstvoices/backend/tests/test_resources/test_widgets_resource.py
firstvoices/pytest.ini
sonar-project.properties

- matched ignore directories of coveragerc and sonar-properties
- Fixed a flaky test related to homepage widget order
- Fixed pytest config to ignore test_resources folder
- Added badges related to code-coverage and build information.
- ~Review the code changes here~
Please checkout this branch locally, and try running the tests through PyCharm or terminal, and verify that the `test_resources` folder is ignored.

Sonar coverage fixes

---

Dockerfile

Add BLAS dependency to docker build

---

firstvoices/backend/serializers/fields.py
firstvoices/backend/serializers/join_request_serializers.py
firstvoices/backend/serializers/user_serializers.py
firstvoices/backend/tests/test_apis/test_join_request_api.py
firstvoices/backend/views/join_request_views.py

- Adds a create and delete API for join requests
- Ensures all reason and statuses are accepted as lowercase (to sync with visibility)
- Adds uniqueness validation for requests and appropriate unit tests
N/A

FW-4340 Join Request Write API

---

README.md
firstvoices/backend/management/commands/_helper.py
firstvoices/backend/management/commands/rebuild_index.py
firstvoices/backend/management/commands/utils/iterators.py
firstvoices/backend/search/tasks/site_tasks.py

Added media index to rebuild management task
N/A

FW-5061 add in media indexing to rebuild management task

---

firstvoices/backend/models/join_request.py
firstvoices/backend/permissions/filters/base.py
firstvoices/backend/permissions/predicates/base.py
firstvoices/backend/permissions/predicates/edit.py
firstvoices/backend/serializers/join_request_serializers.py
firstvoices/backend/serializers/site_serializers.py
firstvoices/backend/tests/test_apis/base_api_test.py
firstvoices/backend/tests/test_apis/test_join_request_api.py
firstvoices/backend/urls.py
firstvoices/backend/views/join_request_views.py

- added these APIs as additional POST endpoints nested under /join-requests
- bonus change: tweaked the permissions for join requests
N/A

Fw-4546, approve/reject/ignore APIs for join requests

---

firstvoices/backend/models/join_request.py
firstvoices/backend/tests/test_apis/test_join_request_api.py

After chatting with Clarissa, updating this to allow staff to make edits
N/A

fw-4546, change join request permissions

---

firstvoices/backend/search/utils/query_builder_utils.py
firstvoices/backend/views/base_views.py

Sentry was reporting an error about a null instance during search, so I checked for any code that didn't handle a missing Alphabet.
N/A

fw-5089, handle null alphabet model for site

---

firstvoices/backend/management/commands/rebuild_index.py
firstvoices/backend/management/commands/utils/iterators.py

Added logging instead of stdout for rebuild_index management command

---

firstvoices/backend/search/utils/hydration_utils.py

Bug fix for missing site context for audio files with speakers
N/A

FW-4671 Media search APIs

---

firstvoices/backend/search/tasks/dictionary_entry_tasks.py
firstvoices/backend/search/tasks/media_tasks.py
firstvoices/backend/search/tasks/site_tasks.py
firstvoices/backend/search/tasks/song_tasks.py
firstvoices/backend/search/tasks/story_tasks.py
firstvoices/backend/search/utils/constants.py

Added a retry_on_conflict parameter to patch the version_conflict_engine_exceptions arising on different servers.
N/A

Fw 5099 add retry on conflict parameter to update operation

---

Dockerfile

* skip caching for installed packages (in Dockerfile), resolves the last sonar warnings for the main branch
N/A

sonar fix - don't cache installed packages

---

.github/dependabot.yml

Bump dependabot checks down to weekly

---

.github/dependabot.yml

fix typo in dependabot file

---

firstvoices/firstvoices/settings.py

- only enable smtp if env var is "True" rather than set to anything
- context: dev and preprod had this set to "False" but it was still enabled
N/A

fw-5075, stricter check to enable smtp

---

firstvoices/healthcheck/views.py

Add environment and build string (commit ID) to healthcheck response
N/A

Add buildstring and environment to healthcheck response

---

README.md
firstvoices/firstvoices/settings.py

moved elastic search config to a config file
N/A

Fw 4701 move elastic search config to a config file

---

sonar-project.properties

Added the ignore to .coveragerc, but forgot to add to sonar-properties with the original PR of FW-5069. 
N/A

added ignore clause for search/tasks to sonar-properties

---

firstvoices/jwt_auth/authentication.py
firstvoices/jwt_auth/tests.py

* add tests for various authentication cases, mostly failures (invalid tokens etc)
N/A

fw-4800, tests for authentication

---

firstvoices/backend/utils/contact_us_utils.py
firstvoices/healthcheck/test_healthcheck.py

This PR adds a health check endpoint test and a typo fix for a contact-us email log message has been added.
N/A

Add healthcheck view test and fix contact us log typo

---

firstvoices/backend/views/search/base_search_views.py

This PR adds a small addition to the API docs describing how to use the media search filter.
N/A

Update media search filter API docs

---

firstvoices/backend/tasks/alphabet_tasks.py

- Refactored the update method for a dictionary entry during alphabet recalculation task
N/A

Refactored the update method for a dictionary entry during alphabet recalculation task

---

firstvoices/backend/management/commands/utils/iterators.py
firstvoices/backend/search/documents/dictionary_entry_document.py
firstvoices/backend/search/query_builder.py
firstvoices/backend/search/tasks/dictionary_entry_tasks.py
firstvoices/backend/search/utils/constants.py
firstvoices/backend/search/utils/query_builder_utils.py
firstvoices/backend/tests/test_search/test_filters.py
firstvoices/backend/views/search/base_search_views.py

- Added has_unrecognized_chars field to dictionary_entry search document
- Added hasUnrecognizedChars as a param to search API
N/A

Fw 5234 add has unrecognized characters flag to search api

---

firstvoices/backend/admin/dictionary_admin.py
firstvoices/backend/views/word_of_the_day_views.py

This PR fixes the slow loading on the WOTD admin view by adding an autocomplete dropdown with pagination.
Additionally, the WOTD endpoint has been optimized by adding prefetching and selecting related models.
N/A

FW-5308 Optimize WOTD admin page and WOTD endpoint

---

firstvoices/backend/serializers/media_serializers.py
firstvoices/backend/tests/test_apis/base_api_test.py
firstvoices/backend/tests/test_apis/base_media_test.py
firstvoices/backend/tests/test_apis/test_audio_api.py
firstvoices/backend/tests/test_apis/test_images_api.py
firstvoices/backend/tests/test_apis/test_videos_api.py
firstvoices/backend/views/audio_views.py
firstvoices/backend/views/image_views.py
firstvoices/backend/views/video_views.py

This PR adds update and patch functionality to the audio/video/image APIs.
N/A

FW-4627 Add media update/patch functionality

---

firstvoices/backend/tests/test_apis/test_category_api.py
firstvoices/backend/views/category_views.py

- Added distinct operator to nested categories when containing a flag
N/A

FW-5425 Added distinct operator to nested categories when containing a flag

---

firstvoices/backend/views/games_views.py

- Fixed a typo for number of seconds in a day that caused same word to be returned.
N/A

FW-5402 wordsy random word bug fix

---

firstvoices/backend/serializers/media_serializers.py
firstvoices/backend/tests/test_apis/base_media_test.py
firstvoices/backend/tests/test_apis/test_dictionary_api.py

This PR adds error handling when invalid URLs are passed to the related video links field.
N/A

FW-4528 Add invalid URL error handling to related video links

---

firstvoices/backend/tests/test_apis/test_story_api.py
firstvoices/backend/views/story_views.py

- Added detail parameter to story API
N/A

FW-5429 Added detail parameter to story API

---

firstvoices/backend/management/commands/_helper.py
firstvoices/backend/management/commands/rebuild_index.py
firstvoices/backend/search/indexing.py

* Finish after rebuilding the language index instead of continuing to the rest
* When requesting a rebuild for an unrecognized index (e.g., "language" vs "languages"), don't rebuild anything. (Formerly would inadvertantly rebuild everything.)
N/A

fw-5297, fix rebuild_index for single index

---

firstvoices/backend/search/signals/dictionary_entry_signals.py
firstvoices/backend/search/utils/constants.py

- change to language index name, and a explaination comment in search signals
- This PR merge will require the previous "language" index to be deleted, and then the "languages" index to be rebuilt.
N/A

Miscellaneous search updates

---

README.md

add languages index to readme

---

firstvoices/firstvoices/settings.py

fw-5553, remove obsolete import

---

firstvoices/backend/search/es_logging.py
firstvoices/backend/tests/test_apis/base_search_test.py
firstvoices/backend/tests/test_apis/test_base_search_viewset.py
firstvoices/backend/views/base_search_views.py

* tests for the common methods in the base search view (getting request parameters, hydrating data, serializing the response)
* bonus change: consolidate the es logs so when we get a message in sentry we can see the full error message at the same time
N/A

Fw-5517, tests for base search view

---

firstvoices/pytest.ini

- added marker for disable_thumbnail_mocks
N/A

FW-5635 Resolve PytestUnknownMarkWarning

---

firstvoices/firstvoices/settings.py

Added CORS_ALLOWED_ORIGIN_REGEXES to django settings
N/A

FW-5364 addition of CORS_ALLOWED_ORIGIN_REGEXES

---

.github/workflows/build.yml

Refactor workflow run conditions

Refactor workflow run conditions

---

firstvoices/backend/models/async_results.py

* Adds a base model for tracking the status of asynchronous jobs, which will be needed for the upcoming bulk-visibility and batch-import APIs
* I added a ticket to eventually update the dictionary recalculation and recalculation preview tasks to use this as well
N/A

Fw-5687, base job model

---

firstvoices/firstvoices/settings.py

- Modified regex string to accept subdomains on localhost
N/A

modified regex string to accept subdomains on localhost

---

.github/workflows/build.yml
firstvoices/backend/tests/test_global_settings.py
firstvoices/firstvoices/settings.py

- Updated base CORS regex and added tests
N/A

Updated base CORS regex and added tests

---

.github/dependabot.yml

- Changed dependabot target branch from "main" to "dev"
N/A

added target-branch to dependabot workflow

---

firstvoices/backend/views/audio_views.py
firstvoices/backend/views/base_views.py
firstvoices/backend/views/bulkvisibilityjob_views.py
firstvoices/backend/views/category_views.py
firstvoices/backend/views/character_views.py
firstvoices/backend/views/contact_us_views.py
firstvoices/backend/views/custom_order_recalculate_views.py
firstvoices/backend/views/dictionary_views.py
firstvoices/backend/views/gallery_views.py
firstvoices/backend/views/games_views.py
firstvoices/backend/views/image_views.py
firstvoices/backend/views/immersion_label_views.py
firstvoices/backend/views/join_request_views.py
firstvoices/backend/views/mtd_data_views.py
firstvoices/backend/views/page_views.py
firstvoices/backend/views/person_views.py
firstvoices/backend/views/search_site_entries_views.py
firstvoices/backend/views/site_feature_views.py
firstvoices/backend/views/song_views.py
firstvoices/backend/views/stats_views.py
firstvoices/backend/views/story_views.py
firstvoices/backend/views/storypage_views.py
firstvoices/backend/views/video_views.py
firstvoices/backend/views/widget_views.py
firstvoices/backend/views/word_of_the_day_views.py

- filter by site id not slug, in all views (performance improvement)
Bonus changes:
- remove unnecessary existence checks for validated site
- update get_validated_site to return a single site
- small refactor for custom get_validated_site in join_request_views
- Insomnia workspace has been updated if applicable
N/A

fw-5765, eliminate unnecessary joins to site table

---

.github/workflows/build.yml
.github/workflows/setup-ffmpeg/action.yml

- Added separate action to try to setup ffmpeg and retry in case the initial fetch fails.
- Ref: https://github.com/federicocarboni/setup-ffmpeg/issues/19
N/A

FW-5693 Added setup-ffmpeg action to add retries

---

firstvoices/backend/serializers/import_job_serializers.py

Adds the specified fields to the ImportReportSerializer Meta class, fixing API docs.
N/A

FW-5818: Add specified fields to ImportReportSerializer

---

firstvoices/backend/serializers/import_job_serializers.py

- Add check for App Membership before site membership
N/A

FW-5598 bug fix - Updated validation for app_role in import_job_serializers

---

firstvoices/backend/models/characters.py
requirements.txt

- Updates g2p to 2.0.0 and fixes any breaking changes.
N/A

FW-5793 Update to g2p 2.0.0

---

firstvoices/backend/models/__init__.py
firstvoices/backend/models/dictionary.py

- Added back dictionary entry removed models
N/A

FW-5867 Added back dictionary entry removed models

---

firstvoices/backend/tests/test_permissions/test_permission_settings.py

- Ignored dictionary entry related models in test_permissions
N/A

FW-5867 Ignored dictionary entry related models in test_permissions

---

firstvoices/backend/management/commands/verify_dictionary_entry_related_models_migration.py

- Added final log messages instead of per entry
N/A

FW-5867 Added final log messages instead of one message per entry

---

firstvoices/backend/management/commands/verify_dictionary_entry_related_models_migration.py

- de-indentation of error logs for dictionary entry related models migration
N/A

FW-5867 de-indentation of error logs for dictionary entry related models migration

---

firstvoices/backend/resources/dictionary.py
firstvoices/backend/resources/utils/import_export_widgets.py

- Added TextListWidget, added the widget to arrayFields for dictionaryEntryResource
N/A

FW-5836 Support importing arrayField attributes for DictionaryEntry model

---

firstvoices/backend/resources/dictionary.py
firstvoices/backend/resources/utils/import_export_widgets.py
firstvoices/backend/tests/factories/resources/import_job/test_upload_all_columns_valid.csv

- Added CategoryWidget to support importing categories in batch uploads
N/A

FW-5837 Add category import support to batch uploads

---

firstvoices/backend/models/media.py

- Fixed deprecation warning for logger by changing method `warn` to `warning`.
N/A

FW-5904 fix depracation warning for logger

---

firstvoices/firstvoices/settings.py
firstvoices/firstvoices/settings_test.py

- Updates STORAGES settings.
- I would recommend doing some more testing for CRUD operations on media files locally before approving/merging this.

FW-5902 Updated STORAGES settings

---

firstvoices/backend/tests/test_apis/test_wotd_api.py
firstvoices/backend/views/word_of_the_day_views.py

- Adds `translations__len__gt=0` to all 3 cases when selecting a word for WOTD
- Adds tests to confirm that the selected words all have translations
N/A

FW-5392 Ensure WOTD endpoint only selects words with translations

---

firstvoices/backend/resources/utils/import_export_widgets.py
firstvoices/backend/tasks/import_job_tasks.py
firstvoices/backend/tests/factories/resources/import_job/original_header_missing.csv
firstvoices/backend/tests/test_tasks/test_import_job_tasks.py

- Added additional validation for missing original header
- Updated TextListField method to skip empty values
N/A

FW-5836 bug fix for importing TextListFields

---

firstvoices/backend/views/api_doc_variables.py
firstvoices/backend/views/character_views.py
firstvoices/backend/views/contact_us_views.py
firstvoices/backend/views/doc_strings.py
firstvoices/backend/views/games_views.py
firstvoices/backend/views/search_all_entries_views.py

Cleaned up the main TODO items in the API docstrings. Messages for the recalculation endpoint were left as-is for now since it is under construction soon.
- Insomnia workspace has been updated if applicable
N/A

FW-5489 clean todos in api docs

---

firstvoices/backend/tasks/build_mtd_export_format_tasks.py

- Added prefetching for the db query
- More improvements are probably necessary, but let's test this with some realistic large dictionaries
N/A

fw-6038, speed up mtd indexing task

---

firstvoices/firstvoices/celery.py

- once overnight instead of every 6 hours
N/A

fw-6044, change schedule for mtd indexing

---

firstvoices/backend/models/mtd.py

- switch non-existant field to self.created instead
N/A

fw-6047, fix mtd export __str__

---

firstvoices/backend/views/dictionary_cleanup_views.py

Adds more detailed documentation for reference when using the dictionary cleanup job and dictionary cleanup job preview.
N/A

FW-6070 Add detailed documentation to dictionary cleanup job and preview

---

firstvoices/backend/resources/dictionary.py
firstvoices/backend/tasks/import_job_tasks.py
firstvoices/backend/tests/factories/import_job_factories.py
firstvoices/backend/tests/test_apis/test_import_job_api.py
firstvoices/backend/tests/test_tasks/test_import_job_tasks.py
firstvoices/backend/urls.py
firstvoices/backend/views/import_job_views.py

- Changed `alt_spelling` to `alternate_spelling`.
- Refactored `import_job_task.batch_import` to get `dry_run` as a flag, and import, validate and raise_errors accordingly.
-  Added a `confirm` action to `import_job_views` to support confirming an import after the dry_run has been successfully completed.
- Added required validations.
N/A

Fw 5604 api to confirm an import

---

firstvoices/backend/admin/admin.py
firstvoices/backend/admin/app_admin.py
firstvoices/backend/admin/dictionary_admin.py
firstvoices/backend/admin/sites_admin.py

* convert word-of-the-day to non-hidden form
* remove inline members, site features, and site menus from site form
* remove nuxeo import status form
N/A

fw-5049, remove extra admin forms

---

firstvoices/backend/resources/base.py
firstvoices/backend/resources/utils/import_export_widgets.py
firstvoices/backend/tests/factories/resources/import_job/boolean_variations.csv
firstvoices/backend/tests/test_tasks/test_import_job_tasks.py

FW-6033 Added column name to validationError for InvertedBooleanFieldWidget

---

.github/workflows/build.yml

- Updated upload-artifact action with change that caused the CI/CD pipeline to fail.
N/A

FW-6110 fix path for coverage file to be uploaded

---

firstvoices/backend/resources/dictionary.py
firstvoices/backend/resources/utils/import_export_widgets.py
firstvoices/backend/tests/factories/resources/import_job/invalid_related_entries.csv
firstvoices/backend/tests/factories/resources/import_job/related_entries.csv
firstvoices/backend/tests/factories/resources/import_job/valid_related_entries.csv
firstvoices/backend/tests/test_tasks/test_import_job_tasks.py

FW-5607 support related entries in batch import

---

.github/workflows/build.yml
Dockerfile
firstvoices/.coveragerc
sonar-project.properties

- Added `relative_files` flag to `.coveragerc` for better sonar coverage analysis
- Merged RUN instructions in Dockerfile since sonar was failing the QC on main
N/A

Minor updates for CI/CD workflow

---

firstvoices/backend/search/documents/dictionary_entry_document.py
firstvoices/backend/search/indexing/dictionary_index.py
firstvoices/backend/search/utils/object_utils.py
firstvoices/backend/tests/test_search_indexing/test_dictionary_indexing.py
firstvoices/backend/tests/test_search_querying/test_object_utils.py

- Added indexing for alternate_spellings in DictionaryEntry
- removed unused utilities leftover from when DictionaryEntry had M2M related attributes
N/A

FW-5943 Indexing for alternate_spellings

---

Dockerfile
firstvoices/firstvoices/logging_utils.py
firstvoices/firstvoices/settings.py
firstvoices/firstvoices/settings_test.py

Reverts First-Peoples-Cultural-Council/fv-be#1046

Revert "FW-5937 Update our log formatter"

---

firstvoices/firstvoices/settings.py

- Added formatting to all logs, which are all currently forwarded to the console.
N/A

FW-5937 Added formatting to all logs

---

firstvoices/firstvoices/settings.py

- Moved a line that redirects logs to the console for anything above the warning level, for now.
N/A

FW-5937 Adding root handler for console logging setup

---

firstvoices/backend/tests/test_apis/test_storypage_api.py
firstvoices/backend/views/storypage_views.py

- Adds prefetching to storypage related media, ordering by "created"
- Bonus: orders storypages by "ordering" in API
- Adds tests for relevant changes
N/A

FW-6132 add storypage prefetching ordering for related media

---

firstvoices/backend/tasks/import_job_tasks.py

- Updating validationStatus under a conditional in import_job_tasks
N/A

FW-6125 Validation status resets to "started" when confirming a import_job fix

---

firstvoices/backend/admin/sites_admin.py

- Currently site media was only syncing if a site feature was changed in the API, this PR adds the sync to admin site operations as well
- Unsure if unit tests for this change were necessary, as the admin site is only for staff use and does not have any prior unit tests.

FW-6156 Add media sync to admin site operations

---

firstvoices/backend/tests/test_commands/test_rebuild_index.py

FW-5999 Automated test for the rebuild_index command

---

firstvoices/.coveragerc
firstvoices/backend/resources/app.py
firstvoices/backend/resources/categories.py
firstvoices/backend/resources/characters.py
firstvoices/backend/resources/join_requests.py
firstvoices/backend/resources/media.py
firstvoices/backend/resources/pages.py
firstvoices/backend/resources/site_homepage_widgets.py
firstvoices/backend/resources/sites.py
firstvoices/backend/resources/songs.py
firstvoices/backend/resources/stories.py
firstvoices/backend/resources/users.py
firstvoices/backend/resources/utils/helpers.py
firstvoices/backend/resources/widgets.py
firstvoices/backend/tests/test_resources/__init__.py
firstvoices/backend/tests/test_resources/test_category_resource.py
firstvoices/backend/tests/test_resources/test_character_resource.py
firstvoices/backend/tests/test_resources/test_join_request_resource.py
firstvoices/backend/tests/test_resources/test_media_resources.py
firstvoices/backend/tests/test_resources/test_membership_resource.py
firstvoices/backend/tests/test_resources/test_pages_resource.py
firstvoices/backend/tests/test_resources/test_site_homepage_widgets.py
firstvoices/backend/tests/test_resources/test_site_resource.py
firstvoices/backend/tests/test_resources/test_song_resource.py
firstvoices/backend/tests/test_resources/test_stories_resource.py
firstvoices/backend/tests/test_resources/test_user_resource.py
firstvoices/backend/tests/test_resources/test_widgets_resource.py
sonar-project.properties

Reverts First-Peoples-Cultural-Council/fv-be#1085

Revert "FW-6187 coverage updates and removal of unused resources"

---

.github/workflows/build.yml
firstvoices/.coveragerc
sonar-project.properties

Reverts First-Peoples-Cultural-Council/fv-be#1084

Revert "Sonar coverage fixes"

---

firstvoices/backend/resources/dictionary.py
firstvoices/backend/tests/factories/resources/import_job/invalid_m2m.csv
firstvoices/backend/tests/test_tasks/test_import_job_tasks.py

- wrapped import_row for DictionaryEntryResource in a transaction
N/A

FW-5605 Wrapping import_row in a transaction

---

firstvoices/backend/serializers/fields.py
firstvoices/backend/tests/test_apis/base_api_test.py
firstvoices/backend/tests/test_apis/test_characters_api.py
firstvoices/backend/tests/test_apis/test_dictionary_api.py
firstvoices/backend/tests/test_apis/test_immersion_label_api.py
firstvoices/backend/tests/utils.py

- Adds arbitrary generated ids to all text list fields
- Updates dictionary entry and related dictionary entry tests to match the new format
N/A

FW-6104 Add ids to text field lists

---

.github/workflows/build.yml
firstvoices/.coveragerc
sonar-project.properties

Reverts First-Peoples-Cultural-Council/fv-be#1089

Revert "Revert "Sonar coverage fixes""

---

requirements.txt

Updates dependencies to upgrade to g2p 2.1.1 (configurable log levels!)
N/A

FW-6112 Upgrade to g2p 2.1.1

---

firstvoices/backend/tests/test_apis/test_search_api.py
firstvoices/backend/views/search_all_entries_views.py

- Removes the blank responses provided by certain invalid search cases and replaces them with paginated responses
- Updates API tests to match
N/A

FW-6213 fix missing pagination in invalid search cases

---

firstvoices/backend/management/commands/import_gallery_data.py
firstvoices/backend/resources/gallery.py
firstvoices/backend/tests/test_commands/test_import_gallery_data.py

- Adds a management command script to read data from local csv files and upload the data as galleries
- Adds a gallery resource to be used to import galleries from nuxeo archive csv files, via django import-export
- Common error case handling is present in both the script and resource
- Logs any import errors to console for importer analysis
N/A

FW-6205 Import Gallery Data

---

firstvoices/backend/models/media.py
firstvoices/backend/tasks/media_tasks.py
firstvoices/backend/tests/test_tasks/test_media_tasks.py

- Adds handling of missing models in the `generate_media_thumbnails` task
- Adds handling of missing original files in the image and video `generate_resized_images` functions
- Adds tests for the two cases
N/A

FW-6188 add handling for missing media in thumbnail generation

---

firstvoices/firstvoices/settings.py
requirements.txt

- Edits the sentry_sdk.init to match this guide: https://docs.sentry.io/platforms/python/migration/1.x-to-2.x
- Upgrades sentry to 2.29.2
N/A

FW-5900 upgrade sentry to 2.19.2

---

firstvoices/backend/tasks/import_job_tasks.py

- Updated the encoding used when generating the FailedRowsCsv file.
-~Migrations have been updated and committed if applicable~
N/A

FW-6282 Encoding fix for FailedRowsCsv

---

requirements.txt

- Resolved dependency conflicts for ES, tablib, numpy and import-export
N/A

Minor dependency updates

---

firstvoices/backend/resources/utils/import_export_widgets.py
firstvoices/backend/tasks/import_job_tasks.py
firstvoices/backend/tests/test_apis/test_import_job_api.py
firstvoices/backend/tests/test_tasks/test_import_job_tasks.py

- Updated PartOfSpeech widget to handle empty values
- Updated import_resource method to clean up failedRowsCsv when there are no errors present
N/A

FW-6361, FW-6367 - Batch import bug fixes

---

firstvoices/backend/models/import_jobs.py
firstvoices/backend/tests/test_models/test_import_job_model.py

- Added status check for import-job delete action.
N/A

FW-6293 Added status check for import-job delete action

---

README.md
firstvoices/backend/management/commands/copy_site.py
firstvoices/backend/tests/test_commands/test_copy_site.py

- Added `copy_site` management command which creates a new site, copies over all content except for JoinRequests, Memberships, Widgets and Pages.
N/A

FW-6225 Add copy_site management command

---

firstvoices/backend/management/commands/copy_site.py

- Added some conditionals for empty ForeignKey handling
N/A

FW-6225 bug fixes for copy_site

---

firstvoices/backend/management/commands/copy_site.py
firstvoices/backend/tests/test_commands/test_copy_site.py

- removed an extra and incorrect conditional statement in copy_site command
N/A

FW-6225 removing an extra and incorrect conditional in copy_site command

---

firstvoices/backend/management/commands/unicode_export.py
firstvoices/backend/tests/test_commands/test_unicode_export.py

* corrects a problem found in qa-- json data is returned as objects not strings, but the test data was using strings
- Insomnia workspace has been updated if applicable
- Signal and Task inventories have been updated if applicable
N/A

fw-6334, correct json test data and correct json data handling for unicode export

---

requirements.txt

Downgrade ES and numpy

---

firstvoices/backend/management/commands/copy_site.py
firstvoices/backend/tests/test_commands/test_copy_site.py

- Added separate method for copying speakers, adding print-counts flag
- Added shared media support
N/A

FW-6225 print-counts flag, shared image library and bug fixes

---

firstvoices/backend/management/commands/copy_site.py

- added case insensitive lookup for shared_media feature flag
N/A

FW-6444 Fix shared media for copy_site command

---

firstvoices/backend/management/commands/copy_site.py

- Added instance.save() in copy_related_media
N/A

FW-6444 Fixed index not updating for instances when shared media is added

---

firstvoices/backend/views/utils.py

- tested locally using the django dev toolbar to count the SQL queries compared to the dev branch
N/A

fw-6458, add prefetching for related documents

---

firstvoices/backend/tests/test_apis/test_dictionary_cleanup_api.py
firstvoices/backend/views/dictionary_cleanup_views.py

- Removes code and tests for the now defunct dictionary-cleanup/clear function
- ~~[ ] Admin Panel has been updated if models have been added or modified~~
- ~~[ ] Migrations have been updated and committed if applicable~~
N/A

FW-6474 Remove dictionary-cleanup/clear function

---

firstvoices/backend/views/document_views.py

- JSONParser missing from DocumentViewSet - resulting in 415 Unsupported error
N/A

FW-6495 Add JSONParser to DocumentViewSet

---

firstvoices/backend/models/media.py

Adds ogg and webm to the list of supported audio in the BE
N/A

FW-6476 Add audio/ogg and audio/webm to supported audio filetypes

---

firstvoices/backend/tasks/import_job_tasks.py
firstvoices/backend/tests/test_tasks/test_import_job_tasks.py

FW-5602 Fix for ImageFile and VideoFile in media validation for batches

---

README.md

- Updates the management commands in the readme to match currently available management commands
- Small grammatical changes and changes for the docker-compose command
N/A

FW-6479 Update readme management commands

---

firstvoices/backend/serializers/search_result_serializers.py
firstvoices/backend/views/base_search_entries_views.py

- When I switched to the search base view, I forgot to add back the prefetching! Fixed now
N/A

fw-6531, add back prefetching for search results

---

firstvoices/backend/management/commands/convert_heic.py
firstvoices/backend/tests/test_commands/test_convert_heic.py

- Adds logging for orphaned heic files
- Adds a case-insensitive check to the django query for filenames
N/A

FW-5140 HEIC bug fixes

---

.github/workflows/build.yml

Added conditional on set-enviornment step in build.yaml for dependabot PRs
N/A

Dependabot actions fix

---

firstvoices/backend/renderers.py
firstvoices/backend/tests/test_exporting/test_export_dictionary.py
firstvoices/backend/views/dictionary_views.py
requirements.txt

fw-6587, add csv renderer for dictionary api

---

firstvoices/backend/importing/importers.py
firstvoices/backend/tasks/import_job_tasks.py
firstvoices/backend/tasks/utils.py
firstvoices/backend/tests/test_tasks/test_import_job_tasks.py

- extract an Importer class for each main resource that is imported
- Importers handle: specifying valid columns, importing data via resources
- no test changes, no functional changes
N/A

Fw-6236, reorganize some importer code

---

firstvoices/backend/serializers/search_result_serializers.py
firstvoices/backend/tests/test_apis/test_search_apis/base_search_test.py
firstvoices/backend/tests/test_apis/test_search_apis/test_base_search_entries_viewset.py
firstvoices/backend/tests/test_apis/test_search_apis/test_base_search_viewset.py

FW-6650 Added created_by and last_modified_by to search serializers

---

firstvoices/backend/tasks/import_job_tasks.py
firstvoices/backend/tests/test_tasks/test_import_job_tasks.py

FW-6539 remove unused media after import job

---

firstvoices/backend/serializers/membership_serializers.py
firstvoices/backend/serializers/site_serializers.py
firstvoices/backend/tests/factories/__init__.py
firstvoices/backend/tests/factories/access.py
firstvoices/backend/tests/factories/membership_factories.py
firstvoices/backend/tests/test_apis/test_membership_api.py
firstvoices/backend/tests/test_apis/test_sites_api.py
firstvoices/backend/urls.py
firstvoices/backend/views/membership_views.py

Add Membership READ api url, serializers, views, and tests.
N/A

FW-4336 Membership read api

---

firstvoices/backend/tasks/import_job_tasks.py
firstvoices/backend/tasks/utils.py
firstvoices/backend/tests/test_tasks/test_import_job_tasks.py

FW-6669 delete failed rows csv

---

firstvoices/backend/tasks/import_job_tasks.py
firstvoices/backend/tests/test_apis/test_import_job_validate_api.py
firstvoices/backend/tests/test_tasks/test_import_job_tasks.py

- Added missing media handling during confirmation step
- ValidationReport only to be generated during dry_run
N/A

Add missing media to batch confirmation workflow

---

firstvoices/backend/models/sites.py
firstvoices/backend/serializers/fields.py
firstvoices/backend/serializers/import_job_serializers.py
firstvoices/backend/serializers/job_serializers.py
firstvoices/backend/serializers/join_request_serializers.py
firstvoices/backend/serializers/membership_serializers.py
firstvoices/backend/serializers/mtd_serializers.py
firstvoices/backend/tests/test_apis/test_membership_api.py
firstvoices/backend/views/join_request_views.py
firstvoices/backend/views/membership_views.py

Adds update and delete apis for site Memberships
N/A

FW-4337 membership update delete

---

firstvoices/backend/views/import_job_views.py
firstvoices/firstvoices/settings.py

- Added `COMPONENT_SPLIT_REQUEST` flag which allows for files to be uploaded through API docs
- Removed id parameter from POST request on import-job
N/A

FW-6715 Upload import-jobs from API docs

---

Dockerfile
requirements.txt

Updated Caddy image to 2.10.0-apline

---

firstvoices/backend/models/story.py
firstvoices/backend/serializers/gallery_serializers.py

- Fixed sonar issues like list comprehension, and set related issues in gallery serializer and story model.
N/A

List comprehension and other sonar fixes.

---

firstvoices/backend/views/person_views.py

FW-6750 Added sort_by name

---

firstvoices/backend/views/page_views.py

FW-6752 - add sort by title to pages

---

firstvoices/backend/tests/test_apis/test_dictionary_export_api.py
firstvoices/backend/views/base_views.py
firstvoices/backend/views/dictionary_export_views.py

FW-6793 Added error handling for dictionary export views
