First-Peoples-Cultural-Council/fv-be

fv_be/app/models.py, fv_be/app/models/__init__.py, fv_be/app/models/base.py, requirements/base.txt
This change adds the base model class which can be inherited by other models. 
The base class contains the following fields:
- id - a UUID
- is_trashed - a field to indicate if the model has been deleted
- created_by - a foreign key to a user
- created - date and time which is automatically updated on creation using the auto_now_add option
- last_modified_by - a foreign key to a user
- last_modified - date and time which is automatically updated when the model is modified using the auto_now option
The date fields are automatically handled and updated but the user fields must be updated when the documents are created or modified.
=> FW-4119 Add base model class

.github/workflows/run-pytest.yml
This PR adds a GitHub Action to run Pytest on PRs targeting the main branch as well as any pushes to the main branch. The workflow caches unchanged dependencies to speed up the workflow runtime.
The following secrets must be set in the repo settings for this workflow to run:
- `ALLOWED_ORIGIN`
- `DB_DATABASE`
- `DB_HOST`
- `DB_PORT`
- `DB_USERNAME`
- `DB_PASSWORD`
The action does correctly fail when a test fails, which can be seen in the following job: https://github.com/NolanVH/fv-be/actions/runs/4854685817/jobs/8652352156
N/A
=> FW-4319 Add GitHub Action to run Pytest on PR

firstvoices/backend/serializers/character_serializers.py, firstvoices/backend/serializers/dictionary_serializers.py, firstvoices/backend/tests/test_apis/test_characters_api.py, firstvoices/backend/views/character_views.py
- added related dictionary entries to response data for character api
- permissions are applied on the related entries
- also narrowed the test for variant response data, since it broke for this unrelated change
N/A
=> fw-4363, add related entries to character api

firstvoices/backend/models/characters.py, firstvoices/backend/serializers/site_data_serializers.py, firstvoices/backend/tests/test_apis/test_sites_data_api.py, firstvoices/backend/urls.py, firstvoices/backend/views/data_views.py, firstvoices/firstvoices/settings.py
These changes add a basic site data export API to give the APP developers a starting point to work with. It is worth noting that this API currently contains some placeholder hardcoded values and will be enhanced as detailed in FW-4347.
The API can be accessed at `/api/1.0/sites/<site-slug>/data/`.
The API contains a `siteDataExport` field containing `config` and `data` objects in the Mother Tongues format. The `config` object contains some site information and a site's alphabet. The `data` object contains an export of dictionary entries.
Planned enhancements to be completed in FW-4347 include the following:
- Pagination of the `data` object
- `audio` and `img` fields contain dynamic content once media upload has been implemented
- Additional fields as needed by the APP developers
- …
=> FW-4202 Site Data API

firstvoices/backend/views/base_views.py, firstvoices/backend/views/category_views.py
Now allows overriding get_list_queryset and get_detail_queryset separately, or just get_queryset
N/A
=> fw-4370, refactor get_list_queryset

firstvoices/scripts/create_local_superadmin_membership.py
Added error handling for when the script tries to add superuser membership for the given email. It previously threw an error if the membership already existed.
N/A
=> Added error handling if a superuser membership is already present

firstvoices/backend/models/characters.py, firstvoices/backend/serializers/dictionary_serializers.py, firstvoices/backend/tests/test_apis/test_dictionary_api.py, firstvoices/backend/tests/test_models/test_alphabet_model.py, firstvoices/backend/tests/test_utils.py, requirements.txt
- Fixes an edge case where valid characters containing ignored characters would make a dictionary entry ineligible for the games character split.
- Bumps g2p version to fix escape characters being added where they should not be. (Thanks to Aidan's incredibly quick fix!)
N/A
=> FW-4377 Fix ignored character edge case

firstvoices/backend/permissions/predicates/base.py, firstvoices/backend/permissions/predicates/view.py, firstvoices/backend/permissions/predicates/view_models.py, firstvoices/backend/tests/test_apis/base_api_test.py, firstvoices/backend/tests/test_permissions/test_predicate_base.py, firstvoices/backend/views/base_views.py
When checking whether a site content should return 403, use a different (more strict) rule than when checking whether the fields of the site model are visible.
N/A
=> fw-4369, check visibility of site, not site summary info

README.md, firstvoices/firstvoices/settings.py
This change allows the admin panel URL to be changed using an environment variable `DJANGO_ADMIN_URL`. The purpose is to increase the security of deployed environments.
N/A
=> FW-4260 Move admin URL to environment variable

firstvoices/backend/serializers/fields.py
Straight refactoring with no visible change in the responses. The SiteHyperlinkedRelatedField and Identity field were making one db request every time they generated a url, in order to get the site slug. This would be reasonable if we were linking to objects from multiple sites, but for all of our current cases we are always linking within the same site. I changed it to reuse the site slug from the view’s kwargs, to eliminate the extra db queries. If multi-site cases come up in the future, we can use NestedHyperlinkedRelatedField.
N/A
=> fw-4409, eliminate db lookup for site content hyperlink fields

firstvoices/backend/models/characters.py, firstvoices/backend/serializers/dictionary_serializers.py, firstvoices/backend/views/base_views.py, firstvoices/backend/views/dictionary_views.py, firstvoices/backend/views/word_of_the_day_views.py
These changes add a context object to the dictionary views which is then passed to the dictionary entry serializer. This context object contains alphabet, ignored character, base character, character variant, and ignorable character information. This information can be collected once and reused during the fetching of each dictionary entry instead of re-querying the database each time.
If testing locally, please try the dictionary list view and detail views and compare the number of queries before and after the changes. The number should at least stay the same or decrease significantly. The changes are more noticeable on a site with a larger number of characters, character variants, ignored characters, and dictionary entries. The number of queries can be seen by using the toolbar in debug …
=> FW-4394 Reduce duplicate queries in dictionary entry views

.gitignore, README.md, firstvoices/scripts/utils/aws_download_utils.py, requirements.txt
This PR adds a small utility script which can be used in the data import tool.
All files are saved in the following location: `firstvoices/scripts/export_data/<timestamp for the file>/<filename>.csv`
The script contains the following core functions (as well as a few helper functions):
- `download_file_from_s3(key)` which takes in a key and saves the corresponding file locally.
- `download_directory_from_s3(directory_name)` which takes in a directory name (or prefix corresponding to a timestamp in the s3 bucket key) and saves all files with that prefix in the key.
- `download_exports_after_timestamp(timestamp)` which takes in a timestamp and will download all files with a timestamp greater than or equal to the input timestamp.
- `download_latest_exports()` finds the most recent timestamp …
=> FW-4416 Add util script to fetch exports from AWS S3 Buckets

firstvoices/backend/serializers/parts_of_speech_serializers.py, firstvoices/backend/tests/test_apis/test_parts_of_speech_api.py, firstvoices/backend/views/parts_of_speech_views.py
This PR changes the parts of speech API such that it return a flat list of all items, and converts the "children" field to a "parent" field. The tests have also been updated to better fit the BaseApiTest class.
N/A
=> FW-4406 Convert Parts of Speech to Flat List

firstvoices/backend/models/category.py, firstvoices/backend/permissions/filters/base.py, firstvoices/backend/permissions/predicates/__init__.py, firstvoices/backend/permissions/predicates/base.py, firstvoices/backend/permissions/predicates/edit.py, firstvoices/backend/permissions/predicates/view_models.py, firstvoices/backend/tests/test_permissions/test_predicate_base.py, firstvoices/backend/tests/test_permissions/test_predicate_edit.py
* staff admins can't edit categories, so i changed the predicates to reflect that
* i moved the edit-specific predicates to their own file and removed the matching filters, since we never need to retrieve a queryset based on edit permissions
N/A
=> fw-4212, remove edit permission for staff admins

firstvoices/backend/search/indices/dictionary_entry_document.py, firstvoices/backend/search/utils/constants.py, firstvoices/backend/search/utils/object_utils.py, firstvoices/backend/search/utils/query_builder_utils.py, firstvoices/backend/tests/test_search/test_query_params.py
- renamed `_id` to `document_id` to have separate postgres and elasticsearch ids
- Added a full_text_search_field where title, translation, notes and parts of speech text are copied to be queried. Title, translation are also queried separately.
- Refactored create/update/delete signals for dictionary_entry index document to reflect the primary key change mentioned above 
- Added subquery for the full_text_search_field and also updated the tests to reflect the change
- Added `notes` update signal, and updated `translation` update signal to add index parts of speech text
- moved ELASTICSEARCH_DICTIONARY_ENTRY_INDEX variable to utils/constants
- Added a function to object_utils to fetch entry from index based on `document_id`
- ~Admin …
=> Fw 4464 add a full text field to mappings and also subquery for full text search

firstvoices/backend/tasks/alphabet_tasks.py, firstvoices/backend/tests/test_tasks/test_alphabet_tasks.py
Minor tweak for recalculation preview task: "unknown character" counts where title has been cleaned.
note: i messed up the jira issue number of my branch -- this PR is correct.
=> FW-4543 recalculation preview unknown char counts

firstvoices/backend/models/media.py, firstvoices/backend/tests/test_models/test_media_models.py
* Missed a spot previously-- this sets the video file dimensions on save
* Moved some code around so pieces could be shared between Video and VideoFile
N/A
=> fw-4383, set video file dimensions on save

firstvoices/backend/search/utils/query_builder_utils.py, firstvoices/backend/tests/test_search/test_query_params.py
Previously the full text search was added to all 3 cases for the `domain` parameter, i.e. `both, language and english`.
This PR limits the full text search to only `both` option. In case of `language` or `english` option, only specific fields will be searched and not the full text field.
The boost values are also adjusted to give priority to exact matches, then fuzzy matches and then the `full_text_search_field`.
N/A
=> FW-4421 Standardize search domain

firstvoices/backend/search/utils/query_builder_utils.py, firstvoices/backend/tests/test_search/test_query_builder_utils.py, firstvoices/backend/tests/test_search/test_query_params.py, firstvoices/backend/views/search/base_search_views.py
updated validation function for `domain`. It now returns `None` internally, which in turn returns empty result set as a response. It defaults to `both` if no or empty input is passed.
N/A
=> FW-4421 refactored get_valid_domain to return None for invalid input

firstvoices/backend/serializers/async_results_serializers.py, firstvoices/backend/serializers/dictionary_serializers.py, firstvoices/backend/serializers/site_serializers.py, firstvoices/backend/serializers/user.py, firstvoices/backend/views/api_doc_variables.py, firstvoices/backend/views/audio_views.py, firstvoices/backend/views/category_views.py, firstvoices/backend/views/character_views.py, firstvoices/backend/views/custom_order_recalculate_views.py, firstvoices/backend/views/data_views.py, firstvoices/backend/views/dictionary_views.py, firstvoices/backend/views/image_views.py, firstvoices/backend/views/person_views.py, firstvoices/backend/views/search/base_search_views.py, firstvoices/backend/views/sites_views.py, firstvoices/backend/views/video_views.py, firstvoices/backend/views/word_of_the_day_views.py
These changes add missing parameters and field types to the `@extend_shema_...` decorators to remove the majority of the warnings when loading the API docs page. Note that nothing has visibly changed as [drf-spectacular](https://github.com/tfranzel/drf-spectacular) will automatically fall back on defaults, but the warnings are now gone. In the future, the API docs page could be updated with things like detailed examples to closely match the expected responses.
N/A
=> FW-4395 Fix API docs warnings

firstvoices/backend/serializers/site_serializers.py, firstvoices/backend/tests/test_apis/test_sites_api.py, firstvoices/backend/views/sites_views.py
* Switched to using a LanguageSerializer in order to add more language fields to the response
* Bonus change: use the simpler permission filters in the site querysets
N/A
=> fw-4555, add language codes to site list api

firstvoices/backend/management/commands/_helper.py, firstvoices/backend/search/indices/dictionary_entry_document.py, firstvoices/backend/search/query_builder.py, firstvoices/backend/search/utils/object_utils.py, firstvoices/backend/search/utils/query_builder_utils.py, firstvoices/backend/tests/test_search/test_query_builder_utils.py, firstvoices/backend/tests/test_search/test_query_params.py, firstvoices/backend/urls.py, firstvoices/backend/views/search/base_search_views.py, firstvoices/backend/views/search/dictionary_search_views.py
dictionary-search api added at `/api/1.0/sites/{{site-slug}}/dictionary-search/` with the following parameters
1. category - Accepts id for a category filter. Returns all the entries associated with the given category or its child categories.
2. startsWithChar - Accepts a char (or combination of chars) and returns entries which has the given char at the beginning.
N/A
=> Fw 4268 implement dictionary search with parameters

firstvoices/backend/models/characters.py, firstvoices/backend/tests/test_models/test_alphabet_model.py
A bugfix with hacky solution. This enables confusables to contain regex special characters and still function -- regex special characters will be correctly recognized in the confusables cleanup process. For example `( -> C` or `h. -> ḥ`
N/A
=> FW-4365 enable confusable cleanup for regex special chars

firstvoices/backend/permissions/filters/view_models.py, firstvoices/backend/permissions/predicates/view_models.py, firstvoices/backend/serializers/membership_serializers.py, firstvoices/backend/tests/test_apis/base_api_test.py, firstvoices/backend/tests/test_apis/test_my_sites_api.py, firstvoices/backend/tests/test_permissions/test_predicate_view_models.py, firstvoices/backend/views/sites_views.py
* Slightly modified the response of the my-sites api, to include the role as well as the site info. 
* To make this simpler, I changed the queryset from a list of Sites to a list of Memberships, which exposed a small problem with the view_membership_model permission. 
* Enabled the standard pagination
* Enabled the detail view, using the site slug as the lookup key
N/A
=> Fw 4550, add role info to my-sites response

firstvoices/backend/pagination.py, firstvoices/backend/tests/test_apis/test_search_api.py, firstvoices/backend/views/search/base_search_views.py
Adds an `override_invalid_number` method to handle invalid page and pageSize values in search pagination parameters. This lets the search proceed, during which the invalid values are handled by the paginator.
N/A
=> FW-4598 Handle invalid page and pageSize values in search Pagination

firstvoices/backend/fixtures/languages.json, firstvoices/backend/resources/base.py, firstvoices/backend/resources/sites.py, firstvoices/backend/tests/test_resources/test_site_resource.py, firstvoices/scripts/import_csv_data.py
Updates languages fixture with some name fixes.
Add language and contact email fields to import tests. Split around some of the import resources so we have a separate SiteResource (creates/updates site fields) and SiteMigrationResource (deletes previous instances and rebuilds site) -- in preparation for a second round site import to update related media fields.
- Pull the branch and test locally
Includes some updates to the languages fixture. These changes were done manually on dev so everything should match. If you want to update your local, especially if …
=> FW-4412 import site model

firstvoices/backend/serializers/page_serializers.py, firstvoices/backend/serializers/site_serializers.py, firstvoices/backend/tests/factories/site_page_factories.py, firstvoices/backend/tests/test_apis/base_api_test.py, firstvoices/backend/tests/test_apis/test_pages_api.py, firstvoices/backend/tests/test_apis/test_sites_api.py, firstvoices/backend/tests/utils.py, firstvoices/backend/urls.py, firstvoices/backend/views/api_doc_variables.py, firstvoices/backend/views/page_views.py
These changes adds the SitePage model list and detail read API at `/api/1.0/sites/{site-slug}/pages` and `/api/1.0/sites/{site-slug}/pages/{page-slug}`.
When reviewing, please check that the widget list order is correct even when a widget belongs to multiple lists with different orders. QA details can be found in [FW-4329](https://firstvoices.atlassian.net/browse/FW-4329).
[FW-4329]: https://firstvoices.atlassian.net/browse/FW-4329?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FW-4329 Add SitePage read API

firstvoices/backend/serializers/site_serializers.py, firstvoices/backend/serializers/widget_serializers.py, firstvoices/backend/tests/test_apis/test_sites_api.py
This PR adds the ability to update the homepage `SiteWidgets` in the site detail update API. A list of `SiteWidget` IDs in the required order can be passed under the homepage field in the request. A `SiteWidgetList` instance for the homepage will be automatically updated or created as needed, as well as the `SiteWidgetListOrder` through models that link the `SiteWidget` instances to the `SiteWidgetList` and provide ordering.
N/A
=> FW-4561 Add homepage to site detail update API

firstvoices/backend/serializers/dictionary_serializers.py, firstvoices/backend/serializers/media_serializers.py, firstvoices/backend/tests/test_apis/test_characters_api.py, firstvoices/backend/tests/test_apis/test_dictionary_api.py, firstvoices/backend/tests/test_apis/test_story_api.py
Add tests for related media in dictionary API as they were already enabled via the mixin.
Bonus change: added unique validators for related media per the request of Guy.
I was going to change the dictionary entry an character's models to better fit the other write API tests (Rob's Story and Songs API) but it seemed like more of a halftime change so I will do it then. Additionally in that halftime PR I will add tests to validate the related media uniqueness validators (tested locally, just not in the unit tests)
=> FW-4605 Add Related Media to Dictionary API

firstvoices/backend/search/utils/query_builder_utils.py, firstvoices/backend/tests/test_search/test_filters.py
Fixed a typo which was causing bug not filtering on `types` parameter properly.
N/A
=> FW-4612-search-api-returning-words-and-phrases-for-word-searches

firstvoices/backend/serializers/media_serializers.py, firstvoices/backend/tests/test_apis/base_api_test.py, firstvoices/backend/tests/test_apis/base_media_test.py, firstvoices/backend/tests/test_apis/test_audio_api.py, firstvoices/backend/tests/test_apis/test_category_api.py, firstvoices/backend/tests/test_apis/test_images_api.py, firstvoices/backend/tests/test_apis/test_person_api.py, firstvoices/backend/tests/test_apis/test_song_api.py, firstvoices/backend/tests/test_apis/test_story_api.py, firstvoices/backend/tests/test_apis/test_videos_api.py, firstvoices/backend/tests/test_apis/test_widgets_api.py
- Added some new assertions in the base tests for create APIs, to check the created instances have the right properties
- Fixed the media property names (underscore vs camel case issue)
N/A
=> Fw-4215, fix for media flag always false

firstvoices/firstvoices/settings.py
* allow a comma-separated list of values in the ALLOWED_ORIGIN environment variable, so we can support multiple sites accessing our server (currently FirstVoices dev and the dev version of the app)
* (single value still works)
N/A
=> fw-4658, allow a list of URLs in allowed_origin

firstvoices/backend/permissions/managers.py, firstvoices/backend/permissions/utils.py, firstvoices/backend/tests/test_permissions/test_permission_settings.py, firstvoices/backend/views/base_views.py
- updated permission tests to compare lists instead of sets, to reveal duplicated results
- added distinct() for all direct uses of the visibility filters (very few-- we mostly use a utility function)
- added a comment in the visible_as_filter function about using distinct()
N/A
=> fw-4607, de-duplicate results

firstvoices/backend/serializers/dictionary_serializers.py, firstvoices/backend/serializers/song_serializers.py, firstvoices/backend/serializers/widget_serializers.py, firstvoices/backend/tests/test_apis/base_api_test.py, firstvoices/backend/tests/test_apis/base_media_test.py, firstvoices/backend/tests/test_apis/test_category_api.py, firstvoices/backend/tests/test_apis/test_characters_api.py, firstvoices/backend/tests/test_apis/test_dictionary_api.py, firstvoices/backend/tests/test_apis/test_pages_api.py, firstvoices/backend/tests/test_apis/test_person_api.py, firstvoices/backend/tests/test_apis/test_song_api.py, firstvoices/backend/tests/test_apis/test_story_api.py, firstvoices/backend/tests/test_apis/test_storypage_api.py, firstvoices/backend/tests/test_apis/test_widgets_api.py, firstvoices/backend/views/base_views.py, firstvoices/backend/views/category_views.py, firstvoices/backend/views/character_views.py, firstvoices/backend/views/dictionary_views.py, firstvoices/backend/views/person_views.py, firstvoices/backend/views/song_views.py, firstvoices/backend/views/story_views.py, firstvoices/backend/views/storypage_views.py, firstvoices/backend/views/widget_views.py
This PR enables PATCH for the following site content APIs:
- Categories at `/api/1.0/sites/{site_slug}/categories/{id}/`
- Characters at `/api/1.0/sites/{site_slug}/characters/{id}/`
- Dictionary at `/api/1.0/sites/{site_slug}/dictionary/{id}/`
- People at `/api/1.0/sites/{site_slug}/people/{id}/`
- Songs at `/api/1.0/sites/{site_slug}/songs/{id}/`
- Stories at `/api/1.0/sites/{site_slug}/stories/{id}/`
- Story Pages at `/api/1.0/sites/{site_slug}/stories/{story_pk}/pages/{id}/`
- Widgets at `/api/1.0/sites/{site_slug}/widgets/{id}/`
For reviewers, it would be good to test at least one of the PATCH API locally.
=> FW-4648 Add PATCH support to Site content APIs

firstvoices/backend/serializers/base_serializers.py, firstvoices/backend/serializers/story_serializers.py, firstvoices/backend/tests/test_apis/base_api_test.py, firstvoices/backend/tests/test_apis/test_storypage_api.py
* switched the the right base test class (for controlled site content) and added the necessary test overrides
* minor: updated the create controlled content permission check for assistants to raise PermissionDenied instead of ValidationError
N/A
=> fw-4368, story page permissions (final.final.this_one)

firstvoices/backend/resources/media.py, firstvoices/backend/tests/test_resources/test_media_resources.py, firstvoices/scripts/import_csv_data.py
Adds import resources for Audio models and AudioSpeaker relations. Updates the import script to include them and adds tests. The AudioSpeaker importer also deletes all Persons from the site that are not part of any AudioSpeaker relation.
Audio objects are migrated with no related file - `original` is left as null.
=> FW-4676 import audio model and audiospeakers

firstvoices/backend/resources/media.py, firstvoices/backend/tests/test_resources/test_media_resources.py
This PR adds the audio file generation by direct database insertion to the Audio data import script.
N/A
=> Add backend_file audio creation on Audio data import

firstvoices/backend/management/commands/import_csv_data.py, firstvoices/backend/resources/app.py, firstvoices/backend/resources/base.py, firstvoices/backend/resources/sites.py, firstvoices/backend/resources/users.py, firstvoices/backend/resources/utils/import_export_widgets.py, firstvoices/backend/tests/test_resources/test_membership_resource.py, firstvoices/backend/tests/test_resources/test_site_resource.py, firstvoices/backend/tests/test_resources/test_user_resource.py
Adds import for app-level and site-level memberships. Skips users with existing app-level memberships (e.g. don't overwrite existing superadmins). Also fixes a bug that appears when re-migrating users -- skip import for users already in the db.
N/A
=> FW-4354 import memberships

firstvoices/backend/admin/base_admin.py, firstvoices/backend/admin/widget_admin.py
This PR includes a fix for SiteWidgetList creation in the admin panel. Widgets should now be added to a SiteWidgetList using the order inline at the bottom of the page at `admin/backend/sitewidgetlist/add/`.
N/A
=> Remove widgets field in SiteWidgetList admin

firstvoices/backend/admin/admin.py, firstvoices/backend/admin/page_admin.py
- admin site speed improvements: eliminate n+1 queries related to the display names for the options in the banner_image, banner_video, logo, homepage, and widgets dropdowns
N/A
=> fw-4735, prefetching for banners + widget lists in admin

firstvoices/backend/tests/test_apis/test_sites_api.py, firstvoices/backend/views/sites_views.py
- correct the permissions in the sites api (were previously being applied to Language but not individual Site objects-- yikes)
N/A
=> fw-4743, don't show team sites without access

firstvoices/backend/models/characters.py, firstvoices/backend/resources/dictionary.py, firstvoices/backend/tests/test_resources/test_dictionary_resources.py
Fix an issue with migrating dictionary entry type as unrecognized. Plus a misc fix for more appropriate warning level on confusables issue.
N/A
=> Fw 4750 fix import dictionary type

firstvoices/backend/management/commands/import_csv_data.py, firstvoices/backend/resources/base.py, firstvoices/backend/resources/characters.py, firstvoices/backend/resources/dictionary.py, firstvoices/backend/resources/stories.py, firstvoices/backend/resources/utils/import_export_widgets.py, firstvoices/backend/tests/test_resources/test_character_resource.py, firstvoices/backend/tests/test_resources/test_stories_resource.py
Adds an import for Story model. Adds reusable components for easily importing ArrayOfStrings and related media. I also figured out the issue with the M2M widget (it was an argument problem), fixed it and updated characters/dictionary.
Potential issues that I will get to later:
- add import for story pages
- fix length of text fields for songs/stories
- have to check if story/songs are limited to 1 cover image
The M2M widget out of the box will silently skip invalid UIDs. If we want it to visibly log an issue with these rows, I can add it, but I don't think …
=> FW-4444 import stories

firstvoices/backend/models/sites.py, firstvoices/backend/permissions/filters/base.py, firstvoices/backend/permissions/filters/view_models.py, firstvoices/backend/permissions/predicates/view.py, firstvoices/backend/permissions/predicates/view_models.py, firstvoices/backend/tests/test_apis/test_sites_api.py, firstvoices/backend/tests/test_permissions/test_predicate_view_models.py, firstvoices/backend/views/base_views.py, firstvoices/backend/views/sites_views.py
- changed model permissions to match ability to access site details (e.g., members can see member site, team members can see team site)
- site list api has custom handling to show summary info for member + public sites
N/A
=> fw-4781, adjust site permissions

firstvoices/backend/serializers/story_serializers.py, firstvoices/backend/tests/test_apis/test_story_api.py, firstvoices/backend/tests/test_apis/test_storypage_api.py
- it helps the frontend to have consistent formats for notes and acknowledgements, and for their purposes it is better to have an id for each item in the list rather than just strings
- rather than change the models at this moment (would impact the data migration), i added arbitrary uids in the serializer
- this means we can change the data models later on without impacting the frontend
N/A
=> fw-4803, add arbitrary uid for notes in story + story page APIs

firstvoices/firstvoices/settings.py, requirements.txt
This PR adds the django-admin-env-notice package with appropriate variables.
**To set up in dev/prod:**
- Set the ENVIRONMENT_NAME env variable to the appropriate name (Dev Server, Prod Server)
- Set the ENVIRONMENT_COLOR to the appropriate colour (any hex code)
For the dev server I would recommend #1dc022 (Green meaning it's okay to make changes)
For the prod server I would recommend #FF0000 (big red banner to let you know it's prod)
=> FW-4403 Add environment banner

firstvoices/backend/management/commands/import_csv_data.py, firstvoices/backend/resources/pages.py, firstvoices/backend/resources/site_homepage_widgets.py, firstvoices/backend/resources/utils/import_export_widgets.py, firstvoices/backend/tests/test_resources/test_site_homepage_widgets.py
This PR adds site homepage widget data migrations. This is done in a separate resource from the original site import while still using the same site CSV. This is because the sites must be imported, followed by the widgets, followed by the site homepage field.
Additionally, the created/modified fields have been added to the SitePage data migration.
N/A
=> FW-4775 Add site homepage widget data migration

firstvoices/backend/fixtures/appjson-defaults.json
* Removed the mobile apps menu item from our default data fixture. 
* This only affects new installations-- existing ones need to be edited. (Already made the switch on beta and dev.)
N/A
=> fw-4854, remove mobile apps from default menu

firstvoices/backend/search/utils/object_utils.py
Added more context parameters to supply to dictionary serializer during hydration of objects in search
- ~README / documentation has been updated if needed
N/A
=> FW-4891 fix errors about missing context in search view

firstvoices/backend/tests/test_apis/test_category_api.py, firstvoices/backend/views/category_views.py
This PR updates the categories list API to return the categories as follows:
- When using nested = true the categories are ordered by parent category title and any children within a parent are ordered by title as well.
- When using nested = false the full list of categories are ordered by title.
N/A
=> FW-4867 Order categories API response alphabetically by title

firstvoices/backend/resources/site_homepage_widgets.py, firstvoices/backend/resources/songs.py, firstvoices/backend/resources/utils/import_export_widgets.py, firstvoices/backend/tests/test_resources/test_song_resource.py, firstvoices/backend/tests/test_resources/test_stories_resource.py
Fix a bug in how empty notes and acknowledgements are imported on Songs. Also tried to add metadata into the site homepage import to keep it from overwriting.
N/A
=> FW-4921 song empty notes fix

firstvoices/backend/resources/songs.py, firstvoices/backend/tests/test_resources/test_song_resource.py
This PR adds a migration for the information held in FVBookEntry documents. If a book entry is a lyric and the notes column contains information then the information is added to the lyric's parent song notes. Each note entry is prefixed with the text "From lyric: " to distinguish notes added this way from other notes.
N/A
=> FW-4922 Add lyric notes migration

firstvoices/backend/management/commands/_helper.py, firstvoices/backend/search/indices/dictionary_entry_document.py, firstvoices/backend/search/indices/song_document.py, firstvoices/backend/search/indices/story_document.py, firstvoices/backend/search/utils/object_utils.py
This PR adds the following three changes:
- Refreshes the dictionary entry/song/story indices when a dictionary entry is saved to allow related field signals to grab the index before the default 1 second has passed between ES updates.
- Adds a category field index update on the m2m_changed signal which is used in the APIs.
- Includes parent category IDs in the index so that dictionary entries will be returned when filtering entries with child categories by a parent category.
N/A
=> FW-4888 Categories search index fixes

firstvoices/backend/tests/test_apis/test_category_api.py, firstvoices/backend/views/category_views.py
This change updates the categories API to return the list of categories in case-insensitive order. For categories with titles "A", "b", and "C" the API will return categories in that order instead of "A", "C", "b".
N/A
=> FW-4923 Update categories API to return in case-insensitive order

firstvoices/backend/search/utils/object_utils.py, firstvoices/backend/serializers/dictionary_serializers.py, firstvoices/backend/tests/test_apis/test_dictionary_api.py
Fixes done to improve the performance for site-wide search (`/api/1.0/sites/{site_slug}/search/`)
- Passing `site` object directly in `context` during hydration process to reduce site lookup from slug
- Adding lookup fields in select_related for dictionary entries hydration. `site,created_by,last_modified_by,part_of_speech`
- Added M2M and foreign key lookups in prefetch_related to reduce additional DB hits and time for the following: `categories,acknowledgement_set,pronunciation_set,note_set,alternatespelling_set,site__language` and prefetch media fields.
- Removed game related fields from dictionary_entry serializer and its related tests. fields: `split_chars,split_chars_base,split_words,split_words_base`. To be added back as a part of …
=> Fw 4807 improve search api response time

firstvoices/backend/admin/media_admin.py
This PR fixes the media files not being removed from AWS when deleting from the admin list view (eg: from `/admin/backend/imagefile/`). When media is deleted this way `delete_queryset` is called which doesn't use the model `delete` method, leaving some orphaned media on AWS in certain cases.
Relates to [FW-4547](https://firstvoices.atlassian.net/browse/FW-4547), [FW-4352](https://firstvoices.atlassian.net/browse/FW-4352), and [FW-4676](https://firstvoices.atlassian.net/browse/FW-4676).
N/A
[FW-4547]: https://firstvoices.atlassian.net/browse/FW-4547?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FW-4352]: https://firstvoices.atlassian.net/browse/FW-4352?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …
=> Fix media files not deleting from AWS using Admin

firstvoices/backend/resources/app.py, firstvoices/backend/resources/media.py, firstvoices/backend/resources/sites.py, firstvoices/backend/resources/users.py, firstvoices/backend/resources/utils/import_export_widgets.py, firstvoices/backend/tests/test_resources/test_media_resources.py, firstvoices/backend/tests/test_resources/test_membership_resource.py, firstvoices/backend/tests/test_resources/test_site_resource.py, firstvoices/backend/tests/test_resources/test_user_resource.py
If import rows have no user metadata (created_by/last_modified_by) add `support@fpcc.ca` in that field instead so the object can be imported. For files inserted directly with SQL, add default `now` timestamps.
N/A
=> FW-4940 import resources allow blank metadata

firstvoices/backend/admin/base_admin.py, firstvoices/backend/admin/dictionary_admin.py, firstvoices/backend/admin/songs_admin.py, firstvoices/backend/admin/story_admin.py
These changes fix the related media bug where the wrong site's media would be listed.
Additionally, this PR updates the related media selector to use the filter_horizontal widget which is more intuitive for large lists.
N/A
=> FW-4935 Fix related media admin bug and update multi-select display

firstvoices/backend/pagination.py, firstvoices/backend/views/audio_views.py
These changes improve the Audio list view database query performance as follows:
- The query to get the pagination object count has been optimized to fetch only the ID instead of all fields on an object reducing the query latency by approximately 75%.
- The get_queryset function in AudioViewSet has been updated to use `prefetch_related` for the site and original relations instead of `select_related`, reducing the query latency by approximately 80%.
- A few of the unneeded fields have been removed from the query selection using `defer`.
- ~Team Postman …
=> FW-4938 Audio list DB performance improvements

.github/workflows/run-pytest.yml
Run the tests with the same python version we use for deployment, to catch any dependency conflicts. Turns out this does not catch the problem we were seeing with numpy 1.26.0, but maybe we'll get lucky next time.
See: https://github.com/First-Peoples-Cultural-Council/fv-be/commit/2ff6ba724f16327e3de6134c2d2e8f4226fd2568
N/A
=> Update run-pytest.yml to match deployed python version

firstvoices/jwt_auth/authentication.py
* Enable caching for jwks signing keys. The library handles refreshing these if the keys are rotated.
N/A
=> fw-4939, cache jwks signing keys

firstvoices/backend/models/media.py
This PR fixes the thumbnail generation error when generating a thumbnail with a small input image that is not a JPEG.
N/A
=> Fix thumbnail generation error when original is not JPEG

.github/workflows/run-pytest.yml, firstvoices/backend/models/media.py, firstvoices/backend/tests/conftest.py, firstvoices/backend/tests/test_models/test_media_models.py, firstvoices/pytest.ini, requirements.debug.txt
- Added pytest-xdist library which allows running tests in parallel reducing the run time from ~23 minutes to ~12 minutes.
- Mocked media dimensions which required ffmpeg before, this does not affect the test suite duration by much. 
N/A
=> FW-4667 Mock ffmpeg to improve test suite run time

.github/workflows/run-pytest.yml, requirements.debug.txt
- Introduced a library called pytest-split, which splits tests into sub-groups.
- Modified workflow to run the above sub-groups in parallel. They are also divided internally into smaller subgroups to take advantage of more than 1 core if present.
- This brings down the time form ~12 minutes to ~6 minutes to run all the tests. 
- ~README / documentation has been updated if needed
N/A
=> FW-4667 Parallel tests with github actions

firstvoices/backend/serializers/base_serializers.py, firstvoices/backend/serializers/song_serializers.py, firstvoices/backend/serializers/story_serializers.py, firstvoices/backend/tests/test_apis/test_song_api.py
* Add arbitrary uids to notes and acknowledgements in song apis, to match our other apis and make life easier for the frontend
N/A
=> fw-4991, uids for song notes and acks

firstvoices/backend/management/commands/convert_lyrics_draftjs_to_text.py, firstvoices/backend/tests/test_commands/__init__.py, firstvoices/backend/tests/test_commands/test_convert_lyrics_draftjs_to_text.py
This PR adds a command to convert all lyric text and lyric translations from draftjs to plain text. The command can be run in the shell as follows: `python manage.py convert_lyrics_draftjs_to_text`.
The script will iterate over all lyrics that don't contain an empty `text` field or an empty `translation` field. If either of those fields contain a draftjs string then the blocks in the draftjs will be looped over. Each text field within the blocks will be pulled out and combined into a single string with a newline delimiter separating each.
For example, a text field containing the following draftjs string:
```
{
"entityMap": {},
"blocks": [
{
"key": "",
"text": "Test line one",
"type": "unstyled",
"depth": 0,
"inlineStyleRanges": [],
"entityRanges": [],
"data": {}
},
{
"key": "",
"text": …
```
=> FW-4995 Add command to convert lyric draftjs to plain text

firstvoices/backend/admin/admin.py, firstvoices/backend/admin/app_admin.py, firstvoices/backend/admin/base_admin.py, firstvoices/backend/admin/characters_admin.py, firstvoices/backend/admin/dictionary_admin.py, firstvoices/backend/admin/media_admin.py, firstvoices/backend/admin/page_admin.py, firstvoices/backend/admin/sites_admin.py, firstvoices/backend/admin/songs_admin.py, firstvoices/backend/admin/story_admin.py, firstvoices/backend/admin/widget_admin.py
This PR contains a large number of admin site performance improvements. 
Notably, the related media selectors have been updated to use `autocomplete_fields` instead of `filter_horizontal`. The `autocomplete_fields` selector has a filterable dropdown that is automatically paginated instead of loading all possible entries. A mixin has been added to `base_admin.py` which allows these `autocomplete_fields` to be auto-filtered, (using `get_search_results`), by site as needed.
Additional queryset `select_related` and `prefetch_related` calls have been added as needed.
Also added autocomplete fields to membership/app membership create/edit (to make it easy to search through long lists).
- …
=> FW-4973 admin performance improvements

firstvoices/backend/serializers/story_serializers.py, firstvoices/backend/tests/test_apis/test_story_api.py, firstvoices/backend/views/story_views.py
This PR adds the ability to update page ordering in the Story update/patch APIs. The endpoints can be passed a "pages" field containing a list of page IDs in the desired order.
Note to @gmcauliffe and @Cara-Barter this will break any places on the frontend where the story update endpoint is used. A list of story page IDs will now need to be passed.
=> FW-4873 Enhance Story update/patch API with page order editing

firstvoices/backend/search/utils/object_utils.py, firstvoices/backend/views/search/base_search_views.py
postgres-document-id replaced by es-document-id in search responses top level "id" field.
N/A
=> FW-4992 postgres-document-id replaced by es-document-id in search responses

firstvoices/.coveragerc, firstvoices/backend/models/constants.py, firstvoices/backend/models/sites.py, firstvoices/backend/models/utils/__init__.py, firstvoices/backend/models/utils/utils.py, firstvoices/backend/models/widget.py, firstvoices/backend/tests/test_apis/test_pages_api.py, firstvoices/backend/tests/test_apis/test_widgets_api.py, firstvoices/backend/tests/test_models/test_site_model.py, firstvoices/backend/tests/test_resources/test_widgets_resource.py, firstvoices/backend/tests/utils.py, firstvoices/pytest.ini
- Added method to generate a set of default widgets when a site is created
- Added a few constants to represent the widgets used for this change, not the complete list
- Ignore tests related to import resources, removed django_coverage_plugin as it is for django templates
- Refactored tests to reflect the new default widgets change
N/A
=> FW-3580 auto generate no settings widgets when creating a site

README.md, firstvoices/firstvoices/settings.py
- kept the insecure key as a fallback for local/debug work
- note that deploying this will log out all admin users and revoke any other uses of secure keys
- note that if this is deployed without setting the appropriate env var, there will be a startup error (intentional)
N/A
=> fw-4961, move django key into env var

firstvoices/backend/serializers/dictionary_serializers.py, firstvoices/backend/serializers/fields.py, firstvoices/backend/serializers/page_serializers.py, firstvoices/backend/serializers/song_serializers.py, firstvoices/backend/serializers/story_serializers.py, firstvoices/backend/serializers/widget_serializers.py, firstvoices/backend/tests/factories/dictionary_entry.py, firstvoices/backend/tests/factories/dictionary_factories.py, firstvoices/backend/tests/test_apis/base_api_test.py, firstvoices/backend/tests/test_apis/base_media_test.py, firstvoices/backend/tests/test_apis/test_category_api.py, firstvoices/backend/tests/test_apis/test_dictionary_api.py, firstvoices/backend/tests/test_apis/test_pages_api.py, firstvoices/backend/tests/test_apis/test_person_api.py, firstvoices/backend/tests/test_apis/test_sites_data_api.py, firstvoices/backend/tests/test_apis/test_song_api.py, firstvoices/backend/tests/test_apis/test_story_api.py, firstvoices/backend/tests/test_apis/test_storypage_api.py, firstvoices/backend/tests/test_apis/test_widgets_api.py
Allow nulls in all optional fields
- In json POST requests, nulls are just omitted. This is reflected in the tests.
- DRF handles this if fields are configured to be required=False and have a default value, so I updated the field configs and removed the NullableCharField we had previously used
- when there is no default for an optional field and the value is null, the default DRF behaviour is to skip setting that value on an update, which seems like a recipe for future bugs for us, so i added base tests and logged a separate ticket (FW-5065) to make sure each api is testing all the relevant values for POST, PUT, and PATCH. (Too much to deal with right now.) I did a pass on the dictionary_entry, song, and story APIs for now.
N/A
=> Fw-4845, allow nulls for optional fields

firstvoices/backend/tests/test_apis/test_join_request_api.py, firstvoices/backend/views/join_request_views.py
- Tweaks the join request API list view to only show `pending` requests.
N/A
=> FW-4339 Only show pending requests in list view API

README.md, firstvoices/backend/management/commands/update_missing_media_metadata.py, firstvoices/backend/models/media.py, firstvoices/backend/tasks/update_metadata_tasks.py, firstvoices/backend/tests/test_tasks/test_update_metadata_tasks.py, firstvoices/firstvoices/settings.py
This PR adds a command to asynchronously update the metadata of any image/video/audio files which are missing metadata. The command queues up three separate Celery workers (one for each of the file types). The command can be executed as follows: `python manage.py update_missing_media_metadata`
The files are updated using the `save` method for each of the models. The following missing metadata on a model instance will trigger a call to `save` for that instance:
- ImageFile
- `mimetype` = None or ""
- `size` = None
- `height` = None or -1 (the default set by the data migrations)
- `width` = None or -1 (the default set by the data migrations)
- VideoFile
- `mimetype` = None or ""
- `size` = None
- `height` = None or -1 (the default set by the data migrations)
- `width` = None or -1 (the …
=> FW-5025 FW-4998 Add missing media file metadata update command

firstvoices/backend/serializers/join_request_serializers.py, firstvoices/backend/tests/test_apis/test_join_request_api.py
- Makes the `status` field of the join request API read-only and always defaults to pending on creation.
N/A
=> FW-4340 Make join request status read only (default to pending)

firstvoices/backend/models/media.py, firstvoices/backend/tests/test_models/test_media_models.py
This PR adds error handling for the case when the ffmpeg probe returns None for the video info.
N/A
=> Add error handling for ffmpeg probe returning none

firstvoices/backend/tasks/send_email_tasks.py, firstvoices/backend/tests/test_apis/test_contact_us_api.py, firstvoices/backend/views/contact_us_views.py
This PR moves the contact-us send_email function to an asynchronous task so that the user does not have to wait for the SMTP server to respond.
N/A
=> Move contact-us email sending to async task

firstvoices/backend/tasks/update_metadata_tasks.py, firstvoices/backend/tests/test_tasks/test_update_metadata_tasks.py
This PR adds additional error handling to ensure the media metadata update command can continue through all of the files without throwing an uncaught exception.
N/A
=> FW-5111 Add additional error handling to media metadata update command

firstvoices/backend/search/utils/hydration_utils.py, firstvoices/backend/search/utils/object_utils.py, firstvoices/backend/serializers/base_serializers.py, firstvoices/backend/serializers/dictionary_serializers.py, firstvoices/backend/serializers/media_serializers.py, firstvoices/backend/serializers/song_serializers.py, firstvoices/backend/serializers/story_serializers.py
- Added a site minimal serializers, which removes a few fields such as url, language from site objects returned as nested objects during any object search such as words, phrases, songs, stories etc.
- Added media related minimal serializers
- Added related_videos to songs and stories minimal serializers as per FE requirement
N/A
=> Remove extra fields from search related serializers

firstvoices/backend/tests/test_apis/test_throttling_limits.py, firstvoices/backend/views/base_views.py, firstvoices/backend/views/contact_us_views.py, firstvoices/backend/views/data_views.py, firstvoices/backend/views/search/base_search_views.py, firstvoices/backend/views/utils.py, firstvoices/firstvoices/settings.py
This PR adds usage throttling. 
As a start, there is both a sustained rate and a burst rate which can be set with the environment variables. They are set as strings in the form of "#/time" where # is the number of requests and time is sec/min/hour/day (eg. "60/min" or "1000/day"). The environment variables are `SUSTAINED_THROTTLE_RATE` and `BURST_THROTTLE_RATE`. If no environment variables are set the sustained rate defaults to 1000 requests per day and the burst rate defaults to 60 requests per minute. 
The variables are set to very high numbers by default if debug is enabled (for local development).
Per user role/API throttling can be added after we launch the new version and have detailed usage statistics.
- ~Admin Panel has been …
=> FW-4945 Add usage throttling

firstvoices/backend/tests/test_apis/test_sites_api.py
Adds an order to all widgets lists to prevent the occasional flaky test failure in homepage APIs.
N/A
=> FW-4926 Fix Flaky Site API Tests

firstvoices/backend/search/query_builder.py, firstvoices/backend/search/utils/query_builder_utils.py, firstvoices/backend/tests/test_search/test_filters.py, firstvoices/backend/tests/test_search/test_query_builder_utils.py, firstvoices/backend/views/search/base_search_views.py
This PR adds a parameter `visibility` to the search API. The parameter adds filtering by document visibility: `Team`, `Members`, and `Public`. 
Note that the results will first be filtered by what the user has permission to view.
N/A
=> FW-5136 Add visibility parameter to the search API

firstvoices/backend/serializers/membership_serializers.py, firstvoices/backend/tests/test_apis/test_my_sites_api.py
my-sites API now returns lowercase visibility value
N/A
=> FW-5165 Casing on visibility values returned by my-sites should be all lowercase

firstvoices/backend/serializers/join_request_serializers.py, firstvoices/backend/tasks/send_email_tasks.py, firstvoices/backend/tests/test_apis/test_join_request_api.py, firstvoices/backend/views/join_request_views.py, firstvoices/backend/views/utils.py
This PR adds email notifications which are sent as follows:
- when a user creates a join request all language admins of the site are notified
- if no language admins exist for the site then a warning is logged, no email is sent, and the join request is still created
- when a join request is approved the user is notified
- when a join request is rejected the user is notified
Additionally, this PR adds a message to all outgoing emails noting that the email is automated and should not be replied to.
Do not merge this PR until the SMTP server has been …
=> FW-5079 and FW-5077 Add join request email notifications

firstvoices/backend/models/sites.py, firstvoices/backend/tests/test_apis/test_join_request_api.py, firstvoices/backend/views/join_request_views.py
Changes permissions such that join request can be added on private sites.
- Adds "join" permission to sites
- Uses join permission in join request view
- Adjusted tests as necessary 
N/A
=> FW-5171 Fix private join requests

firstvoices/backend/management/commands/utils/iterators.py, firstvoices/backend/search/documents/base_document.py, firstvoices/backend/search/documents/dictionary_entry_document.py, firstvoices/backend/search/documents/song_document.py, firstvoices/backend/search/documents/story_document.py, firstvoices/backend/search/query_builder.py, firstvoices/backend/search/tasks/dictionary_entry_tasks.py, firstvoices/backend/search/tasks/song_tasks.py, firstvoices/backend/search/tasks/story_tasks.py, firstvoices/backend/search/utils/get_index_documents.py, firstvoices/backend/search/utils/query_builder_utils.py, firstvoices/backend/tests/test_search/test_filters.py, firstvoices/backend/tests/test_search/test_query_builder_utils.py, firstvoices/backend/views/search/base_search_views.py
This PR adds the following changes:
- `has_audio`, `has_video`, and `has_image` added to dictionary, song, and story search indices (a boolean which returns true if an instance has related media of a type)
- `hasAudio`, `hasVideo`, and `hasImage` added to search parameters
N/A
=> FW-5137 Add media related search parameters

firstvoices/backend/search/utils/constants.py, firstvoices/backend/search/utils/search_term_query.py, firstvoices/backend/tests/test_search/test_query_params.py
- Fuzzy match subqueries will not be added in case of search term having a length of more than **50 characters.**
- Refactored query params related tests to use reusable methods for generating matching queries.
N/A
=> FW-3385 Only exact search for larger queries

firstvoices/backend/resources/join_requests.py, firstvoices/backend/resources/sites.py, firstvoices/backend/tests/test_resources/test_join_request_resource.py, firstvoices/backend/tests/test_resources/test_membership_resource.py
This PR ensures that existing memberships and join requests are skipped during the import process, to allow for partial exports in the nuxeo export script to be imported without errors/having to clear certain models in the db.
This change is implemented for the benefit of testing the remaining migrations on dev/preprod.
N/A
=> FW-5032 Add row skipping and tests for partial export models

firstvoices/backend/management/commands/utils/iterators.py, firstvoices/backend/search/documents/base_document.py, firstvoices/backend/search/tasks/dictionary_entry_tasks.py, firstvoices/backend/search/tasks/media_tasks.py, firstvoices/backend/search/tasks/song_tasks.py, firstvoices/backend/search/tasks/story_tasks.py, firstvoices/backend/search/utils/get_index_documents.py, firstvoices/backend/search/utils/query_builder_utils.py, firstvoices/backend/serializers/dictionary_serializers.py, firstvoices/backend/serializers/media_serializers.py, firstvoices/backend/serializers/song_serializers.py, firstvoices/backend/serializers/story_serializers.py, firstvoices/backend/tests/test_search/test_query_builder_utils.py, firstvoices/backend/views/search/base_search_views.py
This PR adds the ability to order the search results by the following:
- `created`: orders results by the created timestamp
- `modified`: orders results by the last modified timestamp
- `title`: orders results by title based on the alphabet custom order
Results are sorted in ascending order by default and `_desc` can optional get added to the parameter which will sort results in descending order (eg: `sort=created_desc`).
The created and last_modified values have been added to the search index to support these parameters. Additionally, the `created` and `last_modified` values have been added to the serializers used by the search view.
- ~Migrations have been updated …
=> FW-5138 Add order by search parameter

firstvoices/backend/models/async_results.py, firstvoices/backend/serializers/async_results_serializers.py, firstvoices/backend/tasks/alphabet_tasks.py, firstvoices/backend/tests/test_apis/test_dictionary_cleanup_api.py, firstvoices/backend/tests/test_models/test_custom_order_recalculate_model.py, firstvoices/backend/views/custom_order_recalculate_views.py, firstvoices/firstvoices/settings.py
- Moved the db ops to async tasks
- Added a check before starting the next task to verify if there is a task already running.
- Added a separate ticket to JIRA to refactor and reenable the skipped tests.  [FW-5207](https://firstvoices.atlassian.net/browse/FW-5207)
N/A
[FW-5207]: https://firstvoices.atlassian.net/browse/FW-5207?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fw 5154 dictionary recalc move db operations into async tasks

firstvoices/backend/models/characters.py, firstvoices/backend/views/image_views.py, firstvoices/backend/views/video_views.py
- Added caching to 3 properties of the Alphabet model.
- Added a select_related for variant_characters property to resolve N+1 query issue.
- Moved the prefetch_related clause to select_related for ImageViewSet and VideoViewSet to resolve N+1 query issue.
- Added a separate ticket to refactor the base_views to further reduce duplicate and similar queries. Ticket: [FW-5208](https://firstvoices.atlassian.net/browse/FW-5208)
N/A
[FW-5208]: …
=> Fw 5101 fix remaining n 1 query api issues

firstvoices/backend/serializers/site_serializers.py, firstvoices/backend/serializers/stats_serializers.py, firstvoices/backend/tests/test_apis/test_sites_api.py, firstvoices/backend/tests/test_apis/test_stats_api.py, firstvoices/backend/urls.py, firstvoices/backend/views/stats_views.py
Adds a stats API to `/api/1.0/sites/<slug>/stats`
This stats API returns all aggregate and temporal stats provided by the Nuxeo REST API > Statistics endpoint in a very similar format. Also adds tests for these statistics.
Suggestions for data formatting/ quick wins for optimization would be much appreciated, thanks!
=> FW-4521 Add Stats API

firstvoices/firstvoices/settings.py
This PR adds an optional environment variable to allow the sentry error sample rate and the sentry transaction sample rate to be set separately. The environment variable is `SENTRY_ERROR_SAMPLE_RATE`  and is defaulted to 1.0 or 100% of the transactions. See [the sentry docs](https://docs.sentry.io/platforms/python/configuration/options/?original_referrer=https%3A%2F%2Fwww.google.com%2F#sample-rate) for more info.
N/A
=> FW-5223 Add optional variable to set the Sentry error sample rate

firstvoices/backend/admin/join_request_admin.py, firstvoices/backend/tests/test_apis/test_join_request_api.py, firstvoices/backend/views/join_request_views.py
This PR updates the join request list view to order requests by reverse created date (newest first).
Additionally, the admin view for join requests has been updated to add a search field to the sites and users (reducing the number of queries as a bonus).
N/A
=> FW-5210 Order join request list view by reverse created date

firstvoices/jwt_auth/authentication.py, firstvoices/jwt_auth/models.py, firstvoices/jwt_auth/tests.py
* Better http status code for cases of invalid/corrupt tokens, since the problem is a failure to authenticate (401) vs permission denied for a known user (403).
N/A
=> fw-4800, if token is invalid return 401 not 403

firstvoices/backend/models/characters.py, firstvoices/backend/serializers/site_data_serializers.py, firstvoices/backend/tests/test_apis/test_sites_data_api.py, firstvoices/backend/views/data_views.py, firstvoices/firstvoices/settings.py
This PR adds the following changes to the site data API at `/api/1.0/sites/<site  slug>/data`:
- Removed nesting of `data` and `config` inside of `siteDataExport` field
- Add categories list
- Updated audio and image data on `data` entries to now hold actual data instead of placeholder data
- Add pagination to `data` field
- Fixed N+1 query issues and optimized endpoint
N/A
=> FW-4347 enhance site data export API

firstvoices/backend/tests/test_apis/test_dictionary_cleanup_api.py, firstvoices/backend/tests/test_tasks/test_alphabet_tasks.py, firstvoices/backend/views/custom_order_recalculate_views.py, firstvoices/firstvoices/settings_test.py, firstvoices/pytest.ini, requirements.txt
- Refactors all custom order recalculation tests to not use celery
- Removes celery configs from pytest
- Adds the `clear` action to both recalculation endpoints to clear pending tasks if they get "stuck" in PENDING by celery
For admin reference the custom order recalculation process will be documented here: https://firstvoices.atlassian.net/wiki/spaces/FIR/pages/420020253/Custom+Order+Recalculation+Process
=> FW-5207 Refactor dictionary recalculation tests + bugfix

firstvoices/backend/search/query_builder.py, firstvoices/backend/search/utils/query_builder_utils.py, firstvoices/backend/tests/test_search/test_filters.py, firstvoices/backend/tests/test_search/test_query_builder_utils.py, firstvoices/backend/views/search/base_search_views.py
This PR adds the `sort=random` parameter to the search API. When used, results are returned in a random order using the Elastic Search `function_score` and `random_score` functionality (see [the docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html#function-random) for more info).
N/A
=> FW-3233 Add random sort parameter to search

firstvoices/backend/models/media.py
This PR adds a check to the thumbnail color space conversion step. If the mode is not RGB the function will attempt to convert to RGB and will catch the exception and log a message if it fails.
N/A
=> FW-5313 Fix thumbnail generation mode conversion

firstvoices/backend/models/base.py, firstvoices/backend/models/media.py, firstvoices/backend/tasks/alphabet_tasks.py, firstvoices/backend/tasks/update_metadata_tasks.py, firstvoices/backend/tests/test_models/test_character_model.py, firstvoices/backend/tests/test_models/test_dictionary_entry_model.py, firstvoices/backend/tests/test_models/test_media_models.py, firstvoices/backend/tests/test_models/test_site_model.py, firstvoices/backend/tests/test_tasks/test_alphabet_tasks.py
Added a parameter to the save function which allows skipping of any update to the last_modified property. This is applied to the recalculate custom order task. Also fixes a bug about this in the recalculation tests.
N/A
=> FW-5400-fix-recalculation-optional-metadata-onsave

firstvoices/backend/tests/test_apis/test_immersion_label_api.py, firstvoices/backend/views/immersion_label_views.py
- Orders both the list view and `all` view alphabetically by key
- Bonus change: fixes immersion label `all` API doc
- ~~[ ] Admin Panel has been updated if models have been added or modified~~
- ~~[ ] Migrations have been updated and committed if applicable~~
- ~~[ ] Team Postman workspace has been updated if applicable~~
N/A
=> FW-5365 Order Immersion Label List APIs

firstvoices/backend/tests/test_apis/test_games_api.py, firstvoices/backend/tests/utils.py, firstvoices/backend/urls.py, firstvoices/backend/views/games_views.py, firstvoices/firstvoices/settings.py
- Added endpoint to generate config for _wordsy_ game at `/{site_slug}/wordsy`.
- Uses cache for querysets to preserve the config for the given calendar date.
N/A
=> FW-5402 Add wordsy endpoint

firstvoices/backend/models/characters.py, firstvoices/backend/tests/test_models/test_alphabet_model.py
Added additional normalization step after cleaning confusables, to keep data normalized and to prevent bugs in later operations.
N/A
=> FW-5411 normalize after cleaning confusables

firstvoices/backend/tests/test_apis/test_languages_api.py, firstvoices/backend/urls.py, firstvoices/backend/views/language_views.py
* Adds a read-only languages api. This currently duplicates the sites api list view, and then has a detail view that shows one language with its site list. Eventually the sites api list can be switched to a plain list of all sites.
N/A
=> Fw 5284 language api

firstvoices/backend/serializers/dictionary_serializers.py, firstvoices/backend/tests/test_apis/test_dictionary_api.py
Adds the `isImmersionLabel` field to dictionary entries via a read-only serializer method.
If the team would prefer to have this value in the db as a column I could additionally edit the model, but I'm not sure if that's necessary.
=> Add isImmersionLabel field to dictionary entries

firstvoices/backend/serializers/immersion_label_serializers.py, firstvoices/backend/serializers/validators.py, firstvoices/backend/tests/test_apis/test_immersion_label_api.py
- Adds a validator that ensures an object's visbility is greater than or equal to the site's visibility.
- Adds the validator to immersion labels
- Update + add test for the validator
N/A
=> FW-5444 add site visibility validator to immersion labels

firstvoices/backend/management/commands/import_csv_data.py, firstvoices/backend/resources/base.py, firstvoices/backend/tests/test_resources/test_character_resource.py, firstvoices/backend/tests/test_resources/test_dictionary_resources.py, firstvoices/backend/tests/test_resources/test_join_request_resource.py, firstvoices/backend/tests/test_resources/test_membership_resource.py, firstvoices/backend/tests/test_resources/test_song_resource.py, firstvoices/backend/tests/test_resources/test_stories_resource.py, firstvoices/backend/tests/test_resources/test_user_resource.py
Added a field for related video links to the Dictionary, Song, and Story imports. Added testing for video links and reorganized which migration resource tests are skipped.
Note: error-raising is removed from the import script so that we gracefully handle imports onto site data that may have since been deleted (it will skip without failing). And because we are slowly removing support for the import process.
N/A
=> Fw 5381 import embedded video links

firstvoices/backend/tests/test_apis/test_dictionary_cleanup_api.py, firstvoices/backend/views/custom_order_recalculate_views.py
- Adds a check to the `initial` method of the custom order recalculate views to ensure the user is a super user before hitting any of the endpoints in that view.
- Adds better tests to ensure only superadmins are able to use the recalculation endpoints
N/A
=> FW-5487 Add check for superadmin before any recalculation endpoint hits

firstvoices/backend/serializers/gallery_serializers.py, firstvoices/backend/tests/test_apis/test_gallery_api.py
- Adds proper validation in the gallery API for duplicate images
- Adds a test for the validation
I could not use the built-in drf UniqueValidator as the UniqueValidator checks the queryset of the model itself rather than GalleryItem
=> FW-5285 Add proper duplicate image validation to galleries

firstvoices/backend/apps.py, firstvoices/backend/models/__init__.py, firstvoices/backend/models/signals/__init__.py, firstvoices/backend/models/signals/mtd_signals.py, firstvoices/backend/tests/test_tasks/test_mtd_index_rebuild.py
- Added signals to rebuild the mtd language index when relevant models are updated. The signals are placed at `/models/signals/mtd_signals.py`
- There was no need to add additional signals for notes, translations and acknowledgements since if they are to be changed, the dictionary entry is saved, thus the index is rebuilt anyway.
- Added through signals for images and videos.
- Added separate signals for category models with relevant checks to prevent unnecessary rebuilding.
=> Fw 5349 rebuild mtd index when saving a public dictionary entry

firstvoices/backend/permissions/predicates/base.py, firstvoices/backend/permissions/predicates/view.py, firstvoices/backend/permissions/predicates/view_models.py, firstvoices/backend/tests/test_apis/test_my_sites_api.py, firstvoices/backend/tests/test_apis/test_sites_api.py, firstvoices/backend/views/sites_views.py
- Hides hidden sites from the sites list API, regardless of visibility
- Allows access to detail view of hidden sites only if the user is staff or a team member of the hidden site
N/A
=> FW-5432 Hide hidden sites in site APIs

firstvoices/backend/models/sites.py, firstvoices/backend/search/indexing/language_index.py, firstvoices/backend/tests/test_apis/test_languages_api.py, firstvoices/backend/views/search_languages_views.py
* Added a standard filter for "explorable" sites in a new manager for the Site model, to keep this info in one place
N/A
=> fw-5529, handle hidden sites in views and serializers

firstvoices/backend/serializers/media_detail_serializers.py, firstvoices/backend/serializers/page_serializers.py, firstvoices/backend/serializers/utils.py, firstvoices/backend/tests/test_apis/base_api_test.py, firstvoices/backend/tests/test_apis/base_media_test.py, firstvoices/backend/tests/test_apis/test_audio_api.py, firstvoices/backend/tests/test_apis/test_images_api.py, firstvoices/backend/tests/test_apis/test_videos_api.py, firstvoices/backend/views/audio_views.py, firstvoices/backend/views/image_views.py, firstvoices/backend/views/video_views.py
- media detail view now returns a `usage` field which contains instances where the media is used
N/A
=> FW-5021 Add usage field to media retrieve view

firstvoices/backend/serializers/media_serializers.py, firstvoices/backend/tests/test_apis/base_api_test.py, firstvoices/backend/tests/test_apis/base_media_test.py, firstvoices/backend/tests/test_apis/test_audio_api.py, firstvoices/backend/tests/test_apis/test_images_api.py, firstvoices/backend/tests/test_apis/test_videos_api.py, firstvoices/backend/views/audio_views.py, firstvoices/backend/views/image_views.py, firstvoices/backend/views/video_views.py
- updated media APIs to mark the original field as read-only for PUT/PATCH requests
- Added json parser support to all media views. Primarily the use case is for setting the `speakers` to an empty list for audio files.
- Refactored tests to also test for the above cases
N/A
=> FW-4627 Media update APIs original field read-only fix

firstvoices/backend/search/signals/dictionary_entry_signals.py, firstvoices/backend/search/signals/song_signals.py, firstvoices/backend/search/signals/story_signals.py, firstvoices/backend/search/tasks/index_manager_tasks.py, firstvoices/backend/tests/test_search_indexing/base_indexing_tests.py, firstvoices/backend/tests/test_search_indexing/test_dictionary_signals.py
* for the signals on related models, only *update* the index, don't sync it which might call "add_to_index" if the original isn't finished adding yet
N/A
=> fw-5587, prevent adding duplicate items to search index

.github/pull_request_template.md, firstvoices/backend/search/documents/dictionary_entry_document.py, firstvoices/backend/search/query_builder.py, firstvoices/backend/search/utils/constants.py, firstvoices/backend/search/utils/query_builder_utils.py, firstvoices/backend/search/utils/validators.py, firstvoices/backend/tests/test_apis/test_search_api.py, firstvoices/backend/tests/test_search_querying/test_filters.py, firstvoices/backend/tests/test_search_querying/test_query_builder_utils.py, firstvoices/backend/tests/test_search_querying/test_validators.py, firstvoices/backend/views/category_views.py, firstvoices/backend/views/search_all_entries_views.py, firstvoices/backend/views/search_site_entries_views.py
- Added `token_count` as a sub-field to the dictionary entry search documents.
- Added `LENGTH_FILTER_MAX` constant to cap the `maxWords` filter, which points to the `DEFAULT_TITLE_LENGTH` for now.
- Added `minWords` and `maxWords` as a query parameter to the search API. Added relevant filters, sub-query generators, tests and updated documentation accordingly.
- Moved all the validation methods from the `search/utils/query_builder_utils.py` into `search/utils/validators.py`. 
- Updated the github PR templated file to say `insomnia` instead of `Team Postman`.
N/A
=> Fw 5549 implement a length filter to prevent 1 word phrases from being returned for phrase scrambler game

firstvoices/backend/search/indexing/media_index.py, firstvoices/backend/tests/test_search_indexing/test_media_indexing.py
Adds a conditional to the MediaDocumentManager to handle the case where the original file was missing and a matching test.
Currently the original file can be `None` but a separate ticket has been created to determine if that should still be possible. (See https://firstvoices.atlassian.net/browse/FW-5676)
=> FW-5433 Handle missing original file in media indexing

firstvoices/backend/search/signals/dictionary_entry_signals.py, firstvoices/backend/search/signals/site_signals.py, firstvoices/backend/search/signals/song_signals.py, firstvoices/backend/search/signals/story_signals.py, firstvoices/backend/tests/test_search_indexing/base_indexing_tests.py, firstvoices/backend/tests/test_search_indexing/test_dictionary_signals.py, firstvoices/backend/tests/test_search_indexing/test_song_signals.py, firstvoices/backend/tests/test_search_indexing/test_story_signals.py
- Adds the ability to skip search indexing signals if a site has the feature `indexing_paused` enabled
- This pausing applies to all non-media site content that is currently indexed (this is due to the pausing feature being for bulk visibility updates)
Please disregard the test re-runs, sonarcloud is currently having an outage.
=> FW-5685 Allow site indexing signals to be paused

firstvoices/backend/search/indexing/dictionary_index.py, firstvoices/backend/search/indexing/song_index.py, firstvoices/backend/search/indexing/story_index.py, firstvoices/backend/tests/test_apis/test_search_api.py
- sets the hasVideo flag to `true` if a search item with media has an embedded video link
N/A
=> FW-5565 Enable hasVideo flag for video links

firstvoices/backend/models/signals/mtd_signals.py, firstvoices/backend/tests/test_tasks/test_mtd_index_rebuild.py
- Pauses the `request_update_mtd_index` and `store_current_visibility` functions if `indexing_paused` is an enabled feature on the site
N/A
=> FW-5730 Pause MTD dictionary entry indexing when "indexing_paused" is enabled

firstvoices/backend/serializers/job_serializers.py, firstvoices/backend/tests/test_apis/test_bulkvisibility_api.py
- Adds a validation case and test to ensure that `from_visibility` == the site's visibility to prevent users from changing visibility by more than 1 level at a time.
N/A
=> FW-5683 Check that from visibility is equal to site visibilityin bulk visibility API

firstvoices/backend/models/media.py, firstvoices/backend/tests/test_models/test_media_models.py
- Adds `ImageOps.exif_transpose()` to thumbnail generation to remove exif orientation data from original images when generating thumbnails.
- Adds a test to ensure exif orientation data is removed
N/A
=> FW-5583 Fix Thumbnail Orientation

firstvoices/backend/search/tasks/index_manager_tasks.py, firstvoices/backend/search/tasks/site_content_indexing_tasks.py, firstvoices/backend/tasks/alphabet_tasks.py, firstvoices/backend/tasks/build_mtd_export_format.py, firstvoices/backend/tasks/import_job_tasks.py, firstvoices/backend/tasks/media_tasks.py, firstvoices/backend/tasks/send_email_tasks.py, firstvoices/backend/tasks/utils.py, firstvoices/backend/tasks/visibility_tasks.py, firstvoices/backend/tests/test_apis/test_contact_us_api.py, firstvoices/backend/tests/test_search_indexing/base_indexing_tests.py, firstvoices/backend/tests/test_search_indexing/test_site_signals.py, firstvoices/backend/tests/test_tasks/test_alphabet_tasks.py, firstvoices/backend/tests/test_tasks/test_build_mtd.py, firstvoices/backend/tests/test_tasks/test_bulk_visibility.py, firstvoices/backend/tests/test_tasks/test_import_job_tasks.py, firstvoices/backend/tests/test_tasks/test_media_tasks.py, firstvoices/firstvoices/celery.py, firstvoices/firstvoices/settings.py
- Updated celery settings to let it retry on startup, to fix the deprecation warning
- Added logging templates for start and end of a celery task
- Updated all async tasks to log at the start/end/error scenario
N/A
=> FW-5953 Add standardised logging to async tasks

firstvoices/backend/tasks/build_mtd_export_format_tasks.py
Moves the "task end" logging message outside of the loop in the check_sites_for_mtd_sync task
N/A
=> FW-5936 Move task end log out of site loop

firstvoices/backend/tasks/media_tasks.py, firstvoices/backend/tests/test_tasks/test_media_tasks.py
- Media thumbnail generation to not update last modified datetime
N/A
=> FW-5954 Media thumbnail generation to not update last modified datetime

firstvoices/backend/serializers/site_data_serializers.py, firstvoices/backend/tests/test_tasks/test_build_mtd.py
- Slightly edits the `get_img` function of the DictionaryEntryDataSerializer to ignore images that do not have small image thumbnails. This allows bad data in the db to be ignored.
N/A
=> FW-5870 Handle bad image data in site data serializer

firstvoices/backend/models/galleries.py, firstvoices/backend/models/media.py, firstvoices/backend/permissions/predicates/edit.py, firstvoices/backend/tests/factories/access.py, firstvoices/backend/tests/test_apis/base_api_test.py, firstvoices/backend/tests/test_apis/base_media_test.py, firstvoices/backend/tests/test_permissions/test_predicate_edit.py
* update media permissions to allow assistants to add/edit media and galleries (but not persons)
* rename the remaining custom media permission
* add permission tests for media APIs
N/A
=> fw-5326, allow assistants to add/edit media, with tests

firstvoices/backend/tasks/mtd_export_tasks.py, firstvoices/backend/tests/test_apis/test_mtd_data_api.py, firstvoices/backend/tests/test_tasks/test_build_mtd.py
This PR should fix the `Object of type MTDExportJob is not JSON serializable` error in build_index_and_calculate_scores
- Modifies the build_index_and_calculate_scores task to no longer return the MTDExportJob model and just return the id
- Additionally modifies the build_index_and_calculate_scores task to not accept Site models as args passed to tasks should be JSON serializable
- Adjusts tests as necessary
N/A
=> FW-6060 fix build_index_and_calculate_scores accepting and returning models

firstvoices/backend/tasks/mtd_export_tasks.py, firstvoices/backend/tests/test_tasks/test_build_mtd.py
- Prevents the mtd build task from returning an object in the case of a failed or cancelled task the same as https://github.com/First-Peoples-Cultural-Council/fv-be/pull/1042
- Updates tests as necessary
N/A
=> FW-6060 fix MTD task return in fail and cancel states

Dockerfile, firstvoices/firstvoices/logging_utils.py, firstvoices/firstvoices/settings.py, firstvoices/firstvoices/settings_test.py
- Added format settings for logs
- on non-local setups,
`DEBUG` + `INFO` logs will now go to the console, while,
`WARNING` + `ERROR` logs will now go the app.log file
- on local setups, no change in log levels, but the logs will now be more descriptive in the following format
`{levelname}-{asctime}:{pathname} -- {message}`
N/A
=> FW-5937 Update our log formatter

firstvoices/backend/serializers/base_serializers.py, firstvoices/backend/serializers/category_serializers.py, firstvoices/backend/serializers/fields.py, firstvoices/backend/serializers/gallery_serializers.py, firstvoices/backend/serializers/media_serializers.py, firstvoices/backend/serializers/page_serializers.py, firstvoices/backend/serializers/song_serializers.py, firstvoices/backend/serializers/story_serializers.py, firstvoices/backend/tests/test_apis/base_api_test.py, firstvoices/backend/tests/test_apis/base_media_test.py, firstvoices/backend/tests/test_apis/test_bulkvisibility_api.py, firstvoices/backend/tests/test_apis/test_category_api.py, firstvoices/backend/tests/test_apis/test_dictionary_api.py, firstvoices/backend/tests/test_apis/test_dictionary_cleanup_api.py, firstvoices/backend/tests/test_apis/test_gallery_api.py, firstvoices/backend/tests/test_apis/test_immersion_label_api.py, firstvoices/backend/tests/test_apis/test_import_job_api.py, firstvoices/backend/tests/test_apis/test_join_request_api.py, firstvoices/backend/tests/test_apis/test_pages_api.py, firstvoices/backend/tests/test_apis/test_person_api.py, firstvoices/backend/tests/test_apis/test_site_features_api.py, firstvoices/backend/tests/test_apis/test_song_api.py, firstvoices/backend/tests/test_apis/test_story_api.py, firstvoices/backend/tests/test_apis/test_storypage_api.py, firstvoices/backend/tests/test_apis/test_widgets_api.py, firstvoices/backend/utils/character_utils.py
- Adds a `ValidateNonNullableCharFieldsMixin` to most writable serializers, which checks for charfields on the model and if they are null and the field is provided, sets them to "" via the validate method
- Changes the optional charfields serializers to allow_null=true, as validation will set them to "" (otherwise the API automatically returns a 400 error)
- Adds the `test_create_with_null_optional_charfields_success_201` and `test_update_with_null_optional_charfields_success_200` tests to most writable APIs
- Skips the above tests if the API does not have eligible optional charfields
- Unfortunately a `NonNullableCharfield` solution is not viable, as django raises an integrity error if given a null value for a model field that does not allow null values before the `to_internal_value` …
=> FW-5096 convert optional charfields in API to non-nullable

firstvoices/backend/tests/test_apis/test_story_api.py, firstvoices/backend/views/story_views.py, firstvoices/backend/views/storypage_views.py, firstvoices/backend/views/utils.py
- Adds an ordered related media prefetch to story detail and list views, as they display the ordered related media on story pages
- Moves ordered prefetching to `get_created_ordered_media_prefetch_list` function for reuse
- Adds a story view test to verify behaviour
N/A
=> FW-6132 Add prefetching order to story views

firstvoices/backend/resources/base.py, firstvoices/backend/resources/dictionary.py, firstvoices/backend/resources/utils/import_export_widgets.py, firstvoices/backend/tests/factories/resources/import_job/default_values.csv, firstvoices/backend/tests/test_tasks/test_import_job_tasks.py
- Added `default` parameter to `ChoicesWidget` and `InvertedBooleanFieldWidget`.
- Added default values to visibility, type, and boolean field widgets for the `DictionaryEntry` resource.
N/A
=> FW-6126 default values for empty fields in CSV

firstvoices/backend/resources/dictionary.py, firstvoices/backend/serializers/import_job_serializers.py, firstvoices/backend/tasks/import_job_tasks.py, firstvoices/backend/tests/factories/resources/import_job/invalid_dictionary_entries.csv, firstvoices/backend/tests/test_resources/test_dictionary_resources.py, firstvoices/backend/tests/test_tasks/test_import_job_tasks.py
- Added `clean_model_instances` flag to `DictionaryEntry` resource to enable `full_clean` on imported entries.
- The above change required addition of `created_by` and `last_modified_by` fields to the CSV before importing. These fields default back to the user requesting the import if the `run_as_user` field is not supplied.
- added `task_id` to confirm endpoint
- Skip failed_rows_csv generation if no erroneous rows
N/A
=> FW-5604 batch import minor bug fixes

firstvoices/backend/tests/test_celery_settings.py, firstvoices/backend/tests/test_tasks/base_task_test.py, firstvoices/backend/tests/test_tasks/test_build_mtd.py, firstvoices/backend/tests/test_tasks/test_bulk_visibility.py, firstvoices/backend/tests/test_tasks/test_dictionary_cleanup_tasks.py, firstvoices/backend/tests/test_tasks/test_import_job_tasks.py, firstvoices/backend/tests/test_tasks/test_media_tasks.py, firstvoices/backend/tests/test_tasks/test_search_tasks.py, firstvoices/backend/tests/test_tasks/test_send_email_task.py, firstvoices/firstvoices/settings.py
- Sets the CELERY_TASK_IGNORE_RESULT global setting to true
- Adds tests such that each async task is checked that ignore_results is set to true, and that no results are stored in the db
- Bonus: Removed unused blank test file
N/A
=> FW-6007 Ignore celery task results

firstvoices/backend/serializers/gallery_serializers.py, firstvoices/backend/serializers/page_serializers.py, firstvoices/backend/serializers/site_serializers.py
Allow media from other sites, to support shared media. Site logos still enforce the SameSite validator.
N/A
=> fw-6183, allow media from other sites in banners and galleries

firstvoices/backend/search/documents/dictionary_entry_document.py, firstvoices/backend/search/indexing/dictionary_index.py, firstvoices/backend/search/query_builder.py, firstvoices/backend/search/utils/query_builder_utils.py, firstvoices/backend/search/utils/validators.py, firstvoices/backend/tests/test_apis/test_search_api.py, firstvoices/backend/tests/test_search_indexing/test_dictionary_indexing.py, firstvoices/backend/tests/test_search_querying/test_query_params.py, firstvoices/backend/tests/test_search_querying/test_validators.py, firstvoices/backend/views/search_all_entries_views.py, firstvoices/backend/views/search_site_entries_views.py
- Added import-job attribute to the DicitonaryEntry index, and as a parameter to the search API.
- Refactored `get_valid_category` to `validate_model_instance_id` to be reused for import-jobs.
N/A
=> FW-5618 Add import-id parameter to search index and as a parameter to the search API

firstvoices/backend/serializers/site_serializers.py, firstvoices/backend/tests/test_apis/test_sites_api.py
- Ensures has_app site feature is case insensitive when choosing a default site menu
- Updates tests to check insensitivity
N/A
=> FW-6220 Make has_app site feature case insensitive

firstvoices/backend/resources/gallery.py, firstvoices/backend/tests/test_commands/test_import_gallery_data.py
- Adds logic to make an imported galleries cover image the first valid image in the import csv
- Updates tests to check for cover image handling
N/A
=> FW-6205 Add cover image handling to imported galleries

firstvoices/backend/permissions/predicates/edit.py, firstvoices/backend/serializers/base_serializers.py, firstvoices/backend/serializers/story_serializers.py, firstvoices/backend/tests/test_apis/base_api_test.py
- The special handling we added to check visibility when assistants are creating objects is also reused in put and patch requests. This change handles the case where the submitted data does not contain a visibility field, for patch requests.
N/A
=> fw-6366, handle null visibility in PATCH permissions

firstvoices/backend/management/commands/unicode_export.py, firstvoices/backend/tests/test_commands/test_unicode_export.py
* Adds a management command to generate the csv files for the [orthography-resources folder for the unicode-resources repository](https://github.com/First-Peoples-Cultural-Council/unicode-resources/tree/main/orthography-resources)
N/A
=> fw-6334, unicode_export management command with tests

firstvoices/backend/management/commands/convert_mp3_to_audio.py, firstvoices/backend/tests/test_commands/test_convert_mp3_to_audio.py
When converting broken media instances to the correct type, ensure we use a copy of the underlying file content, rather than pointing the new File instance to the same old stored file object. When the old broken media is removed, its associated File (and file object) is deleted, so the new media instance was left with a file path that pointed to nothing.
N/A
=> fw-6436, copy rather than link to mp3 files

firstvoices/backend/management/commands/merge_duplicate_speakers.py, firstvoices/backend/tests/test_commands/test_merge_duplicate_speakers.py
* Management command to merge duplicate speakers based on case-insensitive exact matches on the name (within the same site)
* Merges all audio links
* Keeps the oldest version of the bio
N/A
=> Fw-6450, merge speakers

firstvoices/backend/tests/test_apis/test_import_job_media_api.py, firstvoices/backend/views/import_job_media_views.py
- checks the import job status before allowing more media to be uploaded for that batch import
N/A
=> fw-6429, block uploading more media after an import runs

firstvoices/backend/resources/gallery.py, firstvoices/backend/tests/test_commands/test_import_gallery_data.py
- remove duplicate images while preserving list order, so the first element can be used as the cover
N/A
=> fw-6432, handle duplicate images in gallery import

firstvoices/backend/tests/test_apis/test_search_apis/test_search_api.py, firstvoices/backend/tests/test_apis/test_search_apis/test_search_querying/test_search_entry_results.py, firstvoices/backend/tests/test_apis/test_search_apis/test_site_search_api.py
- convert test_hydrate_objects into a mixin to test serialization of search results in the views
- no functional changes
N/A
=> fw-5518, tests for search API response formatting

firstvoices/backend/tests/test_apis/test_search_apis/test_languages_api.py, firstvoices/backend/views/search_languages_views.py
- param to toggle list of sites from being filtered by user permissions vs "explorable" aka all sites that can be browsed on the explore languages page
- This is a breaking change to the API that would hide some sites on the Explore Languages page, but since we are still pre-1.0 and we are planning to release fv-web at the same time, Guy and I decided this was ok. It makes the default behaviour the same as all the other APIs, which is simpler to remember for the future
N/A
=> fw-6601, add param to language api 

firstvoices/backend/resources/base.py, firstvoices/backend/tasks/dictionary_cleanup_tasks.py, firstvoices/backend/tasks/visibility_tasks.py, firstvoices/backend/tests/test_tasks/test_bulk_visibility.py, firstvoices/backend/tests/test_tasks/test_dictionary_cleanup_tasks.py, firstvoices/backend/tests/test_tasks/test_import_job_tasks.py, firstvoices/backend/tests/test_tasks/test_media_tasks.py
Ensures that all tasks in the [task inventory](https://firstvoices.atlassian.net/wiki/spaces/FIR/pages/832995337/Task+Inventory) are tested to update system_last_modified when creating/modifying an entry in the db.
- `confirm_import_job`: ensure all created dictionary entries/media have a system_last_modified field >= last_modified
- `build_index_and_calculate_scores`: already handled by https://github.com/First-Peoples-Cultural-Council/fv-be/pull/1326
- `bulk_change_visibility`: updates every entry's system_last_modified value as well as visibility
- `cleanup_dictionary`: tests that the system_last_modified value has been updated
- `generate_media_thumbnails`: tests that the system_last_modified value has been updated
N/A
=> FW-6574 All tasks update system last modified

docker-compose.yml, firstvoices/backend/search/documents/base_document.py, firstvoices/backend/search/documents/dictionary_entry_document.py, firstvoices/backend/search/documents/language_document.py, firstvoices/backend/search/documents/media_document.py, firstvoices/backend/search/documents/song_document.py, firstvoices/backend/search/documents/story_document.py, firstvoices/backend/search/indexing/base.py, firstvoices/backend/search/queries/query_builder.py, firstvoices/backend/search/queries/query_builder_utils.py, firstvoices/backend/search/queries/search_term_query.py, firstvoices/backend/search/queries/text_matching.py, firstvoices/backend/tests/test_apis/test_search_apis/base_search_test.py, firstvoices/backend/tests/test_apis/test_search_apis/test_search_api.py, firstvoices/backend/tests/test_apis/test_search_apis/test_site_search_api.py, firstvoices/backend/tests/test_commands/test_rebuild_index.py, firstvoices/backend/tests/test_search_indexing/base_indexing_tests.py, firstvoices/backend/views/base_search_views.py, firstvoices/backend/views/search_languages_views.py, firstvoices/firstvoices/settings.py, requirements.txt
- Required changes for elasticsearch version upgrade from 7.x to 8.x
- `elasticsearch_dsl` is now packaged with the `elasticsearch` package from 8.x. So that package is removed from dependencies and all imports are changed accordingly.
- Elasticsearch image in docker-compose is updated to [8.18.2](https://hub.docker.com/_/elasticsearch).
Note: When pulling the branch locally, you will have to run a new cluster with the updated version. It can be done using stopping/deleting your current ES …
=> FW-6577 Elasticsearch version upgrade

firstvoices/backend/serializers/search_result_serializers.py
- Adds site and related media prefetching to all dictionary entry, song and story search result serializers.
N/A
=> FW-6598 add further prefetching to site results

firstvoices/backend/serializers/export_serializers.py, firstvoices/backend/serializers/fields.py, firstvoices/backend/tests/test_apis/test_export_api.py, firstvoices/backend/tests/test_utils.py, firstvoices/backend/urls.py, firstvoices/backend/utils/CustomCsvRenderer.py, firstvoices/backend/views/base_search_entries_views.py, firstvoices/backend/views/base_search_views.py, firstvoices/backend/views/dictionary_export_views.py, firstvoices/backend/views/search_all_entries_views.py, firstvoices/backend/views/search_site_entries_views.py
- Added Dictionary export api at `/{site_slug}/dictionary-export` with support for all the same parameters as the site-search API. Returns a CSV with the specified filename in the response.
- Added DictionaryExportSerializer that subclasses SearchResultSerializer to build on top of it, added utility read-only fields(`InvertedBooleanField`, `CommaSeparatedIDsField`) to export in the required format.
- Added CustomCSVRenderer that can be used to export any serializer's data output in a CSV format with the option to flatten fields (e.g. notes -> note, note_2, ...).
- Refactored API docs for search views to be reused in dictionary-export API as well.
- Minor refactor base_search_views to pull out a `get_search_response` method to reduce duplicating it in export API.
- ~Admin Panel has been …
=> FW-56, FW-5220 Dictionary export API

firstvoices/backend/management/commands/remove_speaker_links.py, firstvoices/backend/tests/factories/resources/management_commands/remove_speaker_entries_minimal.csv, firstvoices/backend/tests/test_commands/test_remove_speaker_links.py
- Adds a management command to remove audio links from entries when specific spekers are present
- Takes a speaker name, site slug, optional entries csv and an output location for the results csv
- Command can also be run as a dry run to see what audio would be unlinked
N/A
=> FW-5724 Add remove_speaker_links management command

firstvoices/backend/importing/importers.py, firstvoices/backend/resources/base.py, firstvoices/backend/serializers/export_serializers.py, firstvoices/backend/tests/factories/resources/import_job/invalid_video_embed_links.csv, firstvoices/backend/tests/factories/resources/import_job/video_embed_links.csv, firstvoices/backend/tests/test_apis/base/base_media_test.py, firstvoices/backend/tests/test_apis/test_export_api.py, firstvoices/backend/tests/test_tasks/test_import_job_tasks.py, firstvoices/backend/views/dictionary_export_views.py
- Adds import support for the `video_embed_links` field in batch import, containing a comma separated list of youtube or vimeo links
- Modifies the dictionary export such that related video links are exported to a single field: `video_embed_links`
N/A
=> FW-6438 Add related video links to batch import
